# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DownloadSessionsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DownloadSessionDialog(object):
    def setupUi(self, DownloadSessionDialog):
        DownloadSessionDialog.setObjectName("DownloadSessionDialog")
        DownloadSessionDialog.resize(1689, 919)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(DownloadSessionDialog)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.show_reddit_objects_checkbox = QtWidgets.QCheckBox(DownloadSessionDialog)
        self.show_reddit_objects_checkbox.setObjectName("show_reddit_objects_checkbox")
        self.horizontalLayout.addWidget(self.show_reddit_objects_checkbox)
        self.show_posts_checkbox = QtWidgets.QCheckBox(DownloadSessionDialog)
        self.show_posts_checkbox.setObjectName("show_posts_checkbox")
        self.horizontalLayout.addWidget(self.show_posts_checkbox)
        self.show_content_checkbox = QtWidgets.QCheckBox(DownloadSessionDialog)
        self.show_content_checkbox.setObjectName("show_content_checkbox")
        self.horizontalLayout.addWidget(self.show_content_checkbox)
        self.show_comments_checkbox = QtWidgets.QCheckBox(DownloadSessionDialog)
        self.show_comments_checkbox.setObjectName("show_comments_checkbox")
        self.horizontalLayout.addWidget(self.show_comments_checkbox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.splitter = QtWidgets.QSplitter(DownloadSessionDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.download_session_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.download_session_layout.setContentsMargins(0, 0, 0, 0)
        self.download_session_layout.setObjectName("download_session_layout")
        self.download_session_list_view = QtWidgets.QListView(self.verticalLayoutWidget)
        self.download_session_list_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.download_session_list_view.setObjectName("download_session_list_view")
        self.download_session_layout.addWidget(self.download_session_list_view)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.reddit_object_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.reddit_object_layout.setContentsMargins(0, 0, 0, 0)
        self.reddit_object_layout.setObjectName("reddit_object_layout")
        self.reddit_object_list_view = QtWidgets.QListView(self.verticalLayoutWidget_2)
        self.reddit_object_list_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.reddit_object_list_view.setObjectName("reddit_object_list_view")
        self.reddit_object_layout.addWidget(self.reddit_object_list_view)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.post_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.post_layout.setContentsMargins(0, 0, 0, 0)
        self.post_layout.setObjectName("post_layout")
        self.post_table_view = QtWidgets.QTableView(self.verticalLayoutWidget_3)
        self.post_table_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.post_table_view.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.post_table_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.post_table_view.setGridStyle(QtCore.Qt.NoPen)
        self.post_table_view.setObjectName("post_table_view")
        self.post_layout.addWidget(self.post_table_view)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.content_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.content_layout.setContentsMargins(0, 0, 0, 0)
        self.content_layout.setObjectName("content_layout")
        self.content_list_view = QtWidgets.QListView(self.verticalLayoutWidget_4)
        self.content_list_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.content_list_view.setIconSize(QtCore.QSize(0, 0))
        self.content_list_view.setFlow(QtWidgets.QListView.LeftToRight)
        self.content_list_view.setResizeMode(QtWidgets.QListView.Adjust)
        self.content_list_view.setLayoutMode(QtWidgets.QListView.Batched)
        self.content_list_view.setGridSize(QtCore.QSize(0, 0))
        self.content_list_view.setViewMode(QtWidgets.QListView.IconMode)
        self.content_list_view.setBatchSize(10)
        self.content_list_view.setWordWrap(True)
        self.content_list_view.setObjectName("content_list_view")
        self.content_layout.addWidget(self.content_list_view)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.comment_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.comment_layout.setContentsMargins(0, 0, 0, 0)
        self.comment_layout.setObjectName("comment_layout")
        self.comment_tree_view = QtWidgets.QTreeView(self.verticalLayoutWidget_5)
        self.comment_tree_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.comment_tree_view.setObjectName("comment_tree_view")
        self.comment_layout.addWidget(self.comment_tree_view)
        self.verticalLayout_6.addWidget(self.splitter)

        self.retranslateUi(DownloadSessionDialog)
        QtCore.QMetaObject.connectSlotsByName(DownloadSessionDialog)

    def retranslateUi(self, DownloadSessionDialog):
        _translate = QtCore.QCoreApplication.translate
        DownloadSessionDialog.setWindowTitle(_translate("DownloadSessionDialog", "Download Sessions"))
        self.show_reddit_objects_checkbox.setText(_translate("DownloadSessionDialog", "Show reddit objects"))
        self.show_posts_checkbox.setText(_translate("DownloadSessionDialog", "Show posts"))
        self.show_content_checkbox.setText(_translate("DownloadSessionDialog", "Show content"))
        self.show_comments_checkbox.setText(_translate("DownloadSessionDialog", "Show comments"))

