# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DownloaderForRedditSettingsGUI.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsGUI(object):
    def setupUi(self, SettingsGUI):
        SettingsGUI.setObjectName("SettingsGUI")
        SettingsGUI.resize(702, 804)
        self.gridLayout_7 = QtWidgets.QGridLayout(SettingsGUI)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.auto_save_checkbox = QtWidgets.QCheckBox(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.auto_save_checkbox.setFont(font)
        self.auto_save_checkbox.setObjectName("auto_save_checkbox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.auto_save_checkbox)
        self.label = QtWidgets.QLabel(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.backup_select_folder_button = QtWidgets.QPushButton(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.backup_select_folder_button.setFont(font)
        self.backup_select_folder_button.setObjectName("backup_select_folder_button")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.backup_select_folder_button)
        self.label_2 = QtWidgets.QLabel(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.backup_import_file_button = QtWidgets.QPushButton(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.backup_import_file_button.setFont(font)
        self.backup_import_file_button.setObjectName("backup_import_file_button")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.backup_import_file_button)
        self.gridLayout_7.addLayout(self.formLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.imgur_client_button = QtWidgets.QPushButton(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.imgur_client_button.setFont(font)
        self.imgur_client_button.setObjectName("imgur_client_button")
        self.verticalLayout.addWidget(self.imgur_client_button)
        self.reddit_account_link_button = QtWidgets.QPushButton(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.reddit_account_link_button.setFont(font)
        self.reddit_account_link_button.setObjectName("reddit_account_link_button")
        self.verticalLayout.addWidget(self.reddit_account_link_button)
        self.gridLayout_7.addLayout(self.verticalLayout, 0, 1, 1, 2)
        self.line = QtWidgets.QFrame(SettingsGUI)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_7.addWidget(self.line, 1, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.post_limit_label = QtWidgets.QLabel(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.post_limit_label.setFont(font)
        self.post_limit_label.setObjectName("post_limit_label")
        self.horizontalLayout.addWidget(self.post_limit_label)
        self.post_limit_spinbox = QtWidgets.QSpinBox(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.post_limit_spinbox.setFont(font)
        self.post_limit_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.post_limit_spinbox.setAccelerated(True)
        self.post_limit_spinbox.setMinimum(1)
        self.post_limit_spinbox.setMaximum(1000)
        self.post_limit_spinbox.setProperty("value", 25)
        self.post_limit_spinbox.setObjectName("post_limit_spinbox")
        self.horizontalLayout.addWidget(self.post_limit_spinbox)
        self.gridLayout_7.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        self.subreddit_sort_group = QtWidgets.QGroupBox(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subreddit_sort_group.setFont(font)
        self.subreddit_sort_group.setObjectName("subreddit_sort_group")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.subreddit_sort_group)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sub_sort_hot_radio = QtWidgets.QRadioButton(self.subreddit_sort_group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sub_sort_hot_radio.setFont(font)
        self.sub_sort_hot_radio.setObjectName("sub_sort_hot_radio")
        self.gridLayout_2.addWidget(self.sub_sort_hot_radio, 0, 0, 2, 1)
        self.sub_sort_new_radio = QtWidgets.QRadioButton(self.subreddit_sort_group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sub_sort_new_radio.setFont(font)
        self.sub_sort_new_radio.setObjectName("sub_sort_new_radio")
        self.gridLayout_2.addWidget(self.sub_sort_new_radio, 0, 1, 1, 1)
        self.sub_sort_top_radio = QtWidgets.QRadioButton(self.subreddit_sort_group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sub_sort_top_radio.setFont(font)
        self.sub_sort_top_radio.setObjectName("sub_sort_top_radio")
        self.gridLayout_2.addWidget(self.sub_sort_top_radio, 1, 1, 2, 1)
        self.sub_sort_rising_radio = QtWidgets.QRadioButton(self.subreddit_sort_group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sub_sort_rising_radio.setFont(font)
        self.sub_sort_rising_radio.setObjectName("sub_sort_rising_radio")
        self.gridLayout_2.addWidget(self.sub_sort_rising_radio, 2, 0, 1, 1)
        self.sub_sort_controversial_radio = QtWidgets.QRadioButton(self.subreddit_sort_group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sub_sort_controversial_radio.setFont(font)
        self.sub_sort_controversial_radio.setObjectName("sub_sort_controversial_radio")
        self.gridLayout_2.addWidget(self.sub_sort_controversial_radio, 3, 0, 1, 1)
        self.sub_sort_top_combo = QtWidgets.QComboBox(self.subreddit_sort_group)
        self.sub_sort_top_combo.setObjectName("sub_sort_top_combo")
        self.gridLayout_2.addWidget(self.sub_sort_top_combo, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.subreddit_sort_group, 2, 2, 2, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.post_score_limit_spin_box = QtWidgets.QSpinBox(SettingsGUI)
        self.post_score_limit_spin_box.setMaximum(100000)
        self.post_score_limit_spin_box.setObjectName("post_score_limit_spin_box")
        self.gridLayout.addWidget(self.post_score_limit_spin_box, 1, 1, 1, 1)
        self.post_score_combo = QtWidgets.QComboBox(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.post_score_combo.setFont(font)
        self.post_score_combo.setEditable(False)
        self.post_score_combo.setCurrentText("")
        self.post_score_combo.setObjectName("post_score_combo")
        self.gridLayout.addWidget(self.post_score_combo, 1, 0, 1, 1)
        self.restrict_to_score_checkbox = QtWidgets.QCheckBox(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.restrict_to_score_checkbox.setFont(font)
        self.restrict_to_score_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.restrict_to_score_checkbox.setObjectName("restrict_to_score_checkbox")
        self.gridLayout.addWidget(self.restrict_to_score_checkbox, 0, 0, 1, 2)
        self.gridLayout_7.addLayout(self.gridLayout, 3, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.date_restriction_checkbox = QtWidgets.QCheckBox(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.date_restriction_checkbox.setFont(font)
        self.date_restriction_checkbox.setObjectName("date_restriction_checkbox")
        self.gridLayout_5.addWidget(self.date_restriction_checkbox, 0, 0, 1, 1)
        self.restrict_by_custom_date_checkbox = QtWidgets.QCheckBox(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.restrict_by_custom_date_checkbox.setFont(font)
        self.restrict_by_custom_date_checkbox.setObjectName("restrict_by_custom_date_checkbox")
        self.gridLayout_5.addWidget(self.restrict_by_custom_date_checkbox, 1, 0, 1, 1)
        self.date_limit_edit = QtWidgets.QDateTimeEdit(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.date_limit_edit.setFont(font)
        self.date_limit_edit.setCalendarPopup(True)
        self.date_limit_edit.setObjectName("date_limit_edit")
        self.gridLayout_5.addWidget(self.date_limit_edit, 1, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 4, 0, 1, 3)
        self.groupBox_2 = QtWidgets.QGroupBox(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.link_filter_video_checkbox = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.link_filter_video_checkbox.setFont(font)
        self.link_filter_video_checkbox.setObjectName("link_filter_video_checkbox")
        self.gridLayout_4.addWidget(self.link_filter_video_checkbox, 0, 0, 1, 2)
        self.link_filter_image_checkbox = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.link_filter_image_checkbox.setFont(font)
        self.link_filter_image_checkbox.setObjectName("link_filter_image_checkbox")
        self.gridLayout_4.addWidget(self.link_filter_image_checkbox, 0, 2, 1, 1)
        self.link_filter_avoid_duplicates_checkbox = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.link_filter_avoid_duplicates_checkbox.setFont(font)
        self.link_filter_avoid_duplicates_checkbox.setObjectName("link_filter_avoid_duplicates_checkbox")
        self.gridLayout_4.addWidget(self.link_filter_avoid_duplicates_checkbox, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.nsfw_filter_combo = QtWidgets.QComboBox(self.groupBox_2)
        self.nsfw_filter_combo.setObjectName("nsfw_filter_combo")
        self.gridLayout_4.addWidget(self.nsfw_filter_combo, 1, 1, 1, 2)
        self.gridLayout_7.addWidget(self.groupBox_2, 5, 0, 1, 3)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.subreddit_save_location_label = QtWidgets.QLabel(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subreddit_save_location_label.setFont(font)
        self.subreddit_save_location_label.setObjectName("subreddit_save_location_label")
        self.gridLayout_6.addWidget(self.subreddit_save_location_label, 0, 0, 1, 1)
        self.subreddit_save_by_combo = QtWidgets.QComboBox(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subreddit_save_by_combo.setFont(font)
        self.subreddit_save_by_combo.setObjectName("subreddit_save_by_combo")
        self.gridLayout_6.addWidget(self.subreddit_save_by_combo, 0, 1, 1, 1)
        self.name_files_label = QtWidgets.QLabel(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_files_label.setFont(font)
        self.name_files_label.setObjectName("name_files_label")
        self.gridLayout_6.addWidget(self.name_files_label, 1, 0, 1, 1)
        self.name_downloads_by_combo = QtWidgets.QComboBox(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_downloads_by_combo.setFont(font)
        self.name_downloads_by_combo.setObjectName("name_downloads_by_combo")
        self.gridLayout_6.addWidget(self.name_downloads_by_combo, 1, 1, 1, 1)
        self.save_directory_line_edit = QtWidgets.QLineEdit(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.save_directory_line_edit.setFont(font)
        self.save_directory_line_edit.setObjectName("save_directory_line_edit")
        self.gridLayout_6.addWidget(self.save_directory_line_edit, 2, 0, 1, 1)
        self.save_directory_dialog_button = QtWidgets.QPushButton(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_directory_dialog_button.setFont(font)
        self.save_directory_dialog_button.setObjectName("save_directory_dialog_button")
        self.gridLayout_6.addWidget(self.save_directory_dialog_button, 2, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 6, 0, 1, 3)
        self.line_2 = QtWidgets.QFrame(SettingsGUI)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_7.addWidget(self.line_2, 7, 0, 1, 3)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.thread_limit_spinbox = QtWidgets.QSpinBox(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.thread_limit_spinbox.setFont(font)
        self.thread_limit_spinbox.setMaximum(12)
        self.thread_limit_spinbox.setProperty("value", 4)
        self.thread_limit_spinbox.setObjectName("thread_limit_spinbox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.thread_limit_spinbox)
        self.save_undownloaded_content_checkbox = QtWidgets.QCheckBox(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_undownloaded_content_checkbox.setFont(font)
        self.save_undownloaded_content_checkbox.setObjectName("save_undownloaded_content_checkbox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.save_undownloaded_content_checkbox)
        self.gridLayout_7.addLayout(self.formLayout_2, 8, 0, 1, 3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.total_files_downloaded_label = QtWidgets.QLabel(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.total_files_downloaded_label.setFont(font)
        self.total_files_downloaded_label.setObjectName("total_files_downloaded_label")
        self.horizontalLayout_2.addWidget(self.total_files_downloaded_label)
        self.restore_defaults_button = QtWidgets.QPushButton(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.restore_defaults_button.setFont(font)
        self.restore_defaults_button.setObjectName("restore_defaults_button")
        self.horizontalLayout_2.addWidget(self.restore_defaults_button)
        self.save_cancel_button_box = QtWidgets.QDialogButtonBox(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_cancel_button_box.setFont(font)
        self.save_cancel_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.save_cancel_button_box.setCenterButtons(False)
        self.save_cancel_button_box.setObjectName("save_cancel_button_box")
        self.horizontalLayout_2.addWidget(self.save_cancel_button_box)
        self.gridLayout_7.addLayout(self.horizontalLayout_2, 9, 0, 1, 3)
        self.subreddit_sort_group.raise_()
        self.line.raise_()
        self.groupBox_2.raise_()
        self.line_2.raise_()

        self.retranslateUi(SettingsGUI)
        QtCore.QMetaObject.connectSlotsByName(SettingsGUI)

    def retranslateUi(self, SettingsGUI):
        _translate = QtCore.QCoreApplication.translate
        SettingsGUI.setWindowTitle(_translate("SettingsGUI", "Settings"))
        self.auto_save_checkbox.setText(_translate("SettingsGUI", "Save Automatically On Close"))
        self.label.setText(_translate("SettingsGUI", "Backup Lists:"))
        self.backup_select_folder_button.setText(_translate("SettingsGUI", "Select Folder"))
        self.label_2.setText(_translate("SettingsGUI", "Import Backups:"))
        self.backup_import_file_button.setText(_translate("SettingsGUI", "Select File"))
        self.imgur_client_button.setText(_translate("SettingsGUI", "Imgur Client Information"))
        self.reddit_account_link_button.setText(_translate("SettingsGUI", "Link Reddit Account"))
        self.post_limit_label.setText(_translate("SettingsGUI", "Post retreival Limit (Max: 1000)"))
        self.post_limit_spinbox.setToolTip(_translate("SettingsGUI", "<html><head/><body><p><span style=\" font-size:10pt;\">Sets the max number of posts to retrieve from Reddit.  The limit is 1000 posts (this limit is imposed by the reddit api)</span></p></body></html>"))
        self.subreddit_sort_group.setTitle(_translate("SettingsGUI", "Subreddit Sort Type"))
        self.sub_sort_hot_radio.setText(_translate("SettingsGUI", "Hot"))
        self.sub_sort_new_radio.setText(_translate("SettingsGUI", "New"))
        self.sub_sort_top_radio.setText(_translate("SettingsGUI", "Top"))
        self.sub_sort_rising_radio.setText(_translate("SettingsGUI", "Rising"))
        self.sub_sort_controversial_radio.setText(_translate("SettingsGUI", "Controversial"))
        self.restrict_to_score_checkbox.setToolTip(_translate("SettingsGUI", "<html><head/><body><p><span style=\" font-size:10pt;\">If checked, posts will only be downloaded if they are above or below a certain score</span></p></body></html>"))
        self.restrict_to_score_checkbox.setText(_translate("SettingsGUI", "Restrict Download By Score"))
        self.date_restriction_checkbox.setToolTip(_translate("SettingsGUI", "<html><head/><body><p><span style=\" font-size:10pt;\">If checked, only links that have been posted after the date of the last post downloaded by each user will be downloaded.</span></p></body></html>"))
        self.date_restriction_checkbox.setText(_translate("SettingsGUI", "Inforce User Date Limits"))
        self.restrict_by_custom_date_checkbox.setText(_translate("SettingsGUI", "Restrict downloads by cusom date:"))
        self.date_limit_edit.setDisplayFormat(_translate("SettingsGUI", "M/d/yyyy hh:mm:ss"))
        self.groupBox_2.setTitle(_translate("SettingsGUI", "Content Filters"))
        self.link_filter_video_checkbox.setText(_translate("SettingsGUI", "Download Videos"))
        self.link_filter_image_checkbox.setText(_translate("SettingsGUI", "Download Images"))
        self.link_filter_avoid_duplicates_checkbox.setText(_translate("SettingsGUI", "Avoid Duplicates"))
        self.label_3.setText(_translate("SettingsGUI", "NSFW filter:"))
        self.subreddit_save_location_label.setText(_translate("SettingsGUI", "Subreddits save to folder designated by:"))
        self.name_files_label.setText(_translate("SettingsGUI", "Name downloaded files by:"))
        self.save_directory_dialog_button.setText(_translate("SettingsGUI", "Select Save Directory"))
        self.label_4.setText(_translate("SettingsGUI", "Number of simultaneous download threads:"))
        self.thread_limit_spinbox.setToolTip(_translate("SettingsGUI", "<html><head/><body><p><span style=\" font-size:10pt;\">This is the number of download threads that will be spawned to download content simultaneously.  The max number is set based on your computers number of processor cores (real and logical)</span></p></body></html>"))
        self.save_undownloaded_content_checkbox.setToolTip(_translate("SettingsGUI", "<html><head/><body><p>When checked, content that has been extracted but not downloaded will be saved and redownloaded during the next run. This prevents content from having to be extracted more than once</p></body></html>"))
        self.save_undownloaded_content_checkbox.setText(_translate("SettingsGUI", "Save undownloaded content"))
        self.total_files_downloaded_label.setText(_translate("SettingsGUI", "Total Files Downloaded: 0"))
        self.restore_defaults_button.setText(_translate("SettingsGUI", "Restore Defaults"))

