# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DownloaderForRedditGUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1232, 836)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Resources/Images/RedditDownloaderIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horz_splitter = QtWidgets.QSplitter(self.centralwidget)
        self.horz_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.horz_splitter.setObjectName("horz_splitter")
        self.layoutWidget = QtWidgets.QWidget(self.horz_splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.user_count_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_count_label.sizePolicy().hasHeightForWidth())
        self.user_count_label.setSizePolicy(sizePolicy)
        self.user_count_label.setObjectName("user_count_label")
        self.horizontalLayout_4.addWidget(self.user_count_label)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.user_list_search_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.user_list_search_edit.setObjectName("user_list_search_edit")
        self.verticalLayout.addWidget(self.user_list_search_edit)
        self.user_list_view = QtWidgets.QListView(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.user_list_view.setFont(font)
        self.user_list_view.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.user_list_view.setObjectName("user_list_view")
        self.verticalLayout.addWidget(self.user_list_view)
        self.user_lists_combo = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.user_lists_combo.setFont(font)
        self.user_lists_combo.setObjectName("user_lists_combo")
        self.verticalLayout.addWidget(self.user_lists_combo)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_user_button = QtWidgets.QPushButton(self.layoutWidget)
        self.add_user_button.setObjectName("add_user_button")
        self.horizontalLayout.addWidget(self.add_user_button)
        self.remove_user_button = QtWidgets.QPushButton(self.layoutWidget)
        self.remove_user_button.setObjectName("remove_user_button")
        self.horizontalLayout.addWidget(self.remove_user_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.layoutWidget1 = QtWidgets.QWidget(self.horz_splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.subreddit_count_label = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subreddit_count_label.sizePolicy().hasHeightForWidth())
        self.subreddit_count_label.setSizePolicy(sizePolicy)
        self.subreddit_count_label.setObjectName("subreddit_count_label")
        self.horizontalLayout_5.addWidget(self.subreddit_count_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.subreddit_list_search_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.subreddit_list_search_edit.setObjectName("subreddit_list_search_edit")
        self.verticalLayout_2.addWidget(self.subreddit_list_search_edit)
        self.subreddit_list_view = QtWidgets.QListView(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subreddit_list_view.setFont(font)
        self.subreddit_list_view.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.subreddit_list_view.setObjectName("subreddit_list_view")
        self.verticalLayout_2.addWidget(self.subreddit_list_view)
        self.subreddit_list_combo = QtWidgets.QComboBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subreddit_list_combo.setFont(font)
        self.subreddit_list_combo.setObjectName("subreddit_list_combo")
        self.verticalLayout_2.addWidget(self.subreddit_list_combo)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_subreddit_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.add_subreddit_button.setObjectName("add_subreddit_button")
        self.horizontalLayout_2.addWidget(self.add_subreddit_button)
        self.remove_subreddit_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.remove_subreddit_button.setObjectName("remove_subreddit_button")
        self.horizontalLayout_2.addWidget(self.remove_subreddit_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.widget = QtWidgets.QWidget(self.horz_splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.download_button_layout = QtWidgets.QHBoxLayout()
        self.download_button_layout.setObjectName("download_button_layout")
        self.download_button = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.download_button.setFont(font)
        self.download_button.setObjectName("download_button")
        self.download_button_layout.addWidget(self.download_button)
        self.soft_stop_download_button = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.soft_stop_download_button.setFont(font)
        self.soft_stop_download_button.setObjectName("soft_stop_download_button")
        self.download_button_layout.addWidget(self.soft_stop_download_button)
        self.terminate_download_button = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.terminate_download_button.setFont(font)
        self.terminate_download_button.setObjectName("terminate_download_button")
        self.download_button_layout.addWidget(self.terminate_download_button)
        self.verticalLayout_3.addLayout(self.download_button_layout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.download_users_radio = QtWidgets.QRadioButton(self.widget)
        self.download_users_radio.setObjectName("download_users_radio")
        self.horizontalLayout_3.addWidget(self.download_users_radio)
        self.download_subreddits_radio = QtWidgets.QRadioButton(self.widget)
        self.download_subreddits_radio.setObjectName("download_subreddits_radio")
        self.horizontalLayout_3.addWidget(self.download_subreddits_radio)
        self.constain_to_sub_list_radio = QtWidgets.QRadioButton(self.widget)
        self.constain_to_sub_list_radio.setObjectName("constain_to_sub_list_radio")
        self.horizontalLayout_3.addWidget(self.constain_to_sub_list_radio)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.output_box = QtWidgets.QTextBrowser(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.output_box.setFont(font)
        self.output_box.setObjectName("output_box")
        self.verticalLayout_3.addWidget(self.output_box)
        self.verticalLayout_4.addWidget(self.horz_splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1232, 31))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuLists = QtWidgets.QMenu(self.menubar)
        self.menuLists.setObjectName("menuLists")
        self.file_export_user_list = QtWidgets.QMenu(self.menuLists)
        self.file_export_user_list.setObjectName("file_export_user_list")
        self.file_export_subreddit_list = QtWidgets.QMenu(self.menuLists)
        self.file_export_subreddit_list.setObjectName("file_export_subreddit_list")
        self.menuUser_Finder = QtWidgets.QMenu(self.menubar)
        self.menuUser_Finder.setObjectName("menuUser_Finder")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.view_sort_lists_by = QtWidgets.QMenu(self.menuView)
        self.view_sort_lists_by.setObjectName("view_sort_lists_by")
        self.view_sort_order = QtWidgets.QMenu(self.menuView)
        self.view_sort_order.setObjectName("view_sort_order")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.file_add_user_list = QtWidgets.QAction(MainWindow)
        self.file_add_user_list.setObjectName("file_add_user_list")
        self.file_add_subreddit_list = QtWidgets.QAction(MainWindow)
        self.file_add_subreddit_list.setObjectName("file_add_subreddit_list")
        self.file_save = QtWidgets.QAction(MainWindow)
        self.file_save.setObjectName("file_save")
        self.file_remove_user_list = QtWidgets.QAction(MainWindow)
        self.file_remove_user_list.setObjectName("file_remove_user_list")
        self.file_remove_subreddit_list = QtWidgets.QAction(MainWindow)
        self.file_remove_subreddit_list.setObjectName("file_remove_subreddit_list")
        self.file_open_settings = QtWidgets.QAction(MainWindow)
        self.file_open_settings.setObjectName("file_open_settings")
        self.file_exit = QtWidgets.QAction(MainWindow)
        self.file_exit.setObjectName("file_exit")
        self.file_failed_download_list = QtWidgets.QAction(MainWindow)
        self.file_failed_download_list.setObjectName("file_failed_download_list")
        self.file_open_user_finder = QtWidgets.QAction(MainWindow)
        self.file_open_user_finder.setObjectName("file_open_user_finder")
        self.download_session_menu_item = QtWidgets.QAction(MainWindow)
        self.download_session_menu_item.setObjectName("download_session_menu_item")
        self.file_unfinished_downloads = QtWidgets.QAction(MainWindow)
        self.file_unfinished_downloads.setObjectName("file_unfinished_downloads")
        self.file_imgur_credits = QtWidgets.QAction(MainWindow)
        self.file_imgur_credits.setObjectName("file_imgur_credits")
        self.file_about = QtWidgets.QAction(MainWindow)
        self.file_about.setObjectName("file_about")
        self.file_user_list_count = QtWidgets.QAction(MainWindow)
        self.file_user_list_count.setObjectName("file_user_list_count")
        self.file_subreddit_list_count = QtWidgets.QAction(MainWindow)
        self.file_subreddit_list_count.setObjectName("file_subreddit_list_count")
        self.file_user_manual = QtWidgets.QAction(MainWindow)
        self.file_user_manual.setObjectName("file_user_manual")
        self.file_check_for_updates = QtWidgets.QAction(MainWindow)
        self.file_check_for_updates.setObjectName("file_check_for_updates")
        self.view_sort_list_by_name = QtWidgets.QAction(MainWindow)
        self.view_sort_list_by_name.setCheckable(True)
        self.view_sort_list_by_name.setObjectName("view_sort_list_by_name")
        self.view_sort_list_by_date_added = QtWidgets.QAction(MainWindow)
        self.view_sort_list_by_date_added.setCheckable(True)
        self.view_sort_list_by_date_added.setObjectName("view_sort_list_by_date_added")
        self.view_sort_list_by_number_of_downloads = QtWidgets.QAction(MainWindow)
        self.view_sort_list_by_number_of_downloads.setCheckable(True)
        self.view_sort_list_by_number_of_downloads.setObjectName("view_sort_list_by_number_of_downloads")
        self.view_order_by_ascending = QtWidgets.QAction(MainWindow)
        self.view_order_by_ascending.setCheckable(True)
        self.view_order_by_ascending.setObjectName("view_order_by_ascending")
        self.view_order_by_descending = QtWidgets.QAction(MainWindow)
        self.view_order_by_descending.setCheckable(True)
        self.view_order_by_descending.setObjectName("view_order_by_descending")
        self.file_open_save_file_location = QtWidgets.QAction(MainWindow)
        self.file_open_save_file_location.setObjectName("file_open_save_file_location")
        self.file_import_save_file = QtWidgets.QAction(MainWindow)
        self.file_import_save_file.setObjectName("file_import_save_file")
        self.export_user_list_as_text_menu_item = QtWidgets.QAction(MainWindow)
        self.export_user_list_as_text_menu_item.setObjectName("export_user_list_as_text_menu_item")
        self.export_user_list_as_json_menu_item = QtWidgets.QAction(MainWindow)
        self.export_user_list_as_json_menu_item.setObjectName("export_user_list_as_json_menu_item")
        self.export_sub_list_as_text_menu_item = QtWidgets.QAction(MainWindow)
        self.export_sub_list_as_text_menu_item.setObjectName("export_sub_list_as_text_menu_item")
        self.export_sub_list_as_json_menu_item = QtWidgets.QAction(MainWindow)
        self.export_sub_list_as_json_menu_item.setObjectName("export_sub_list_as_json_menu_item")
        self.export_sub_list_as_xml_menu_item = QtWidgets.QAction(MainWindow)
        self.export_sub_list_as_xml_menu_item.setObjectName("export_sub_list_as_xml_menu_item")
        self.export_user_list_as_xml_menu_item = QtWidgets.QAction(MainWindow)
        self.export_user_list_as_xml_menu_item.setObjectName("export_user_list_as_xml_menu_item")
        self.file_ffmpeg_requirement = QtWidgets.QAction(MainWindow)
        self.file_ffmpeg_requirement.setObjectName("file_ffmpeg_requirement")
        self.menuFile.addAction(self.file_open_settings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.file_save)
        self.menuFile.addAction(self.file_import_save_file)
        self.menuFile.addAction(self.file_open_save_file_location)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.file_exit)
        self.file_export_user_list.addAction(self.export_user_list_as_text_menu_item)
        self.file_export_user_list.addAction(self.export_user_list_as_json_menu_item)
        self.file_export_user_list.addAction(self.export_user_list_as_xml_menu_item)
        self.file_export_subreddit_list.addAction(self.export_sub_list_as_text_menu_item)
        self.file_export_subreddit_list.addAction(self.export_sub_list_as_json_menu_item)
        self.file_export_subreddit_list.addAction(self.export_sub_list_as_xml_menu_item)
        self.menuLists.addAction(self.file_add_user_list)
        self.menuLists.addAction(self.file_add_subreddit_list)
        self.menuLists.addSeparator()
        self.menuLists.addAction(self.file_remove_user_list)
        self.menuLists.addAction(self.file_remove_subreddit_list)
        self.menuLists.addSeparator()
        self.menuLists.addAction(self.file_export_user_list.menuAction())
        self.menuLists.addAction(self.file_export_subreddit_list.menuAction())
        self.menuLists.addSeparator()
        self.menuLists.addAction(self.file_failed_download_list)
        self.menuLists.addAction(self.file_unfinished_downloads)
        self.menuLists.addSeparator()
        self.menuUser_Finder.addAction(self.file_open_user_finder)
        self.menuHelp.addAction(self.file_imgur_credits)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.file_user_manual)
        self.menuHelp.addAction(self.file_ffmpeg_requirement)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.file_check_for_updates)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.file_about)
        self.view_sort_lists_by.addAction(self.view_sort_list_by_name)
        self.view_sort_lists_by.addAction(self.view_sort_list_by_date_added)
        self.view_sort_lists_by.addAction(self.view_sort_list_by_number_of_downloads)
        self.view_sort_order.addAction(self.view_order_by_ascending)
        self.view_sort_order.addAction(self.view_order_by_descending)
        self.menuView.addAction(self.view_sort_lists_by.menuAction())
        self.menuView.addAction(self.view_sort_order.menuAction())
        self.menuView.addSeparator()
        self.menuView.addAction(self.download_session_menu_item)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuLists.menuAction())
        self.menubar.addAction(self.menuUser_Finder.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Downloader for Reddit"))
        self.label_2.setText(_translate("MainWindow", "Users:"))
        self.user_count_label.setText(_translate("MainWindow", "0"))
        self.user_list_search_edit.setPlaceholderText(_translate("MainWindow", "Search users"))
        self.user_lists_combo.setToolTip(_translate("MainWindow", "Current user list"))
        self.add_user_button.setText(_translate("MainWindow", "Add User"))
        self.remove_user_button.setText(_translate("MainWindow", "Remove User"))
        self.label_4.setText(_translate("MainWindow", "Subreddits:"))
        self.subreddit_count_label.setText(_translate("MainWindow", "0"))
        self.subreddit_list_search_edit.setPlaceholderText(_translate("MainWindow", "Search subreddits"))
        self.subreddit_list_combo.setToolTip(_translate("MainWindow", "Current subreddit list"))
        self.add_subreddit_button.setText(_translate("MainWindow", "Add Subreddit"))
        self.remove_subreddit_button.setText(_translate("MainWindow", "Remove Subreddit"))
        self.download_button.setToolTip(_translate("MainWindow", "Download selected user or subreddit list"))
        self.download_button.setText(_translate("MainWindow", "Download"))
        self.soft_stop_download_button.setToolTip(_translate("MainWindow", "Stops the current download, but allows in progress downloads to finish"))
        self.soft_stop_download_button.setText(_translate("MainWindow", "Stop Download"))
        self.terminate_download_button.setToolTip(_translate("MainWindow", "Stops the download immediately and terminates in progress downloads (may result in corrupted files for downloads that were not complete)"))
        self.terminate_download_button.setText(_translate("MainWindow", "Terminate Download"))
        self.download_users_radio.setToolTip(_translate("MainWindow", "Download only user list"))
        self.download_users_radio.setText(_translate("MainWindow", "Users"))
        self.download_subreddits_radio.setToolTip(_translate("MainWindow", "Download only subreddit list"))
        self.download_subreddits_radio.setText(_translate("MainWindow", "Subreddits"))
        self.constain_to_sub_list_radio.setToolTip(_translate("MainWindow", "<html><head/><body><p>Download user list, but only extract posts made to subreddits in the subreddit list</p></body></html>"))
        self.constain_to_sub_list_radio.setText(_translate("MainWindow", "Constrain Users To Subreddit List"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuLists.setTitle(_translate("MainWindow", "Lists"))
        self.file_export_user_list.setTitle(_translate("MainWindow", "Export User List"))
        self.file_export_subreddit_list.setTitle(_translate("MainWindow", "Export Subreddit List"))
        self.menuUser_Finder.setTitle(_translate("MainWindow", "User Finder"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.view_sort_lists_by.setTitle(_translate("MainWindow", "Sort Lists By"))
        self.view_sort_order.setTitle(_translate("MainWindow", "Sort Order"))
        self.file_add_user_list.setText(_translate("MainWindow", "Add User List"))
        self.file_add_subreddit_list.setText(_translate("MainWindow", "Add Subreddit List"))
        self.file_save.setText(_translate("MainWindow", "Save"))
        self.file_remove_user_list.setText(_translate("MainWindow", "Remove User List"))
        self.file_remove_subreddit_list.setText(_translate("MainWindow", "Remove Subreddit List"))
        self.file_open_settings.setText(_translate("MainWindow", "Settings"))
        self.file_exit.setText(_translate("MainWindow", "Exit"))
        self.file_failed_download_list.setText(_translate("MainWindow", "Failed Download List"))
        self.file_failed_download_list.setToolTip(_translate("MainWindow", "Display the failed download list for the last download session"))
        self.file_open_user_finder.setText(_translate("MainWindow", "Open User Finder"))
        self.download_session_menu_item.setText(_translate("MainWindow", "Download Sessions"))
        self.file_unfinished_downloads.setText(_translate("MainWindow", "Unfinished Downloads"))
        self.file_imgur_credits.setText(_translate("MainWindow", "Imgur Credits"))
        self.file_about.setText(_translate("MainWindow", "About"))
        self.file_user_list_count.setText(_translate("MainWindow", "User List Count:"))
        self.file_subreddit_list_count.setText(_translate("MainWindow", "Subreddit List Count:"))
        self.file_user_manual.setText(_translate("MainWindow", "User Manual"))
        self.file_check_for_updates.setText(_translate("MainWindow", "Check For Update"))
        self.view_sort_list_by_name.setText(_translate("MainWindow", "Name"))
        self.view_sort_list_by_date_added.setText(_translate("MainWindow", "Date Added"))
        self.view_sort_list_by_number_of_downloads.setText(_translate("MainWindow", "Number of Downloads"))
        self.view_order_by_ascending.setText(_translate("MainWindow", "Ascending"))
        self.view_order_by_descending.setText(_translate("MainWindow", "Descending"))
        self.file_open_save_file_location.setText(_translate("MainWindow", "Open Save Location"))
        self.file_import_save_file.setText(_translate("MainWindow", "Import Save File"))
        self.export_user_list_as_text_menu_item.setText(_translate("MainWindow", "Export As Text"))
        self.export_user_list_as_json_menu_item.setText(_translate("MainWindow", "Export As Json"))
        self.export_sub_list_as_text_menu_item.setText(_translate("MainWindow", "Export As Text"))
        self.export_sub_list_as_json_menu_item.setText(_translate("MainWindow", "Export As Json"))
        self.export_sub_list_as_xml_menu_item.setText(_translate("MainWindow", "Export As Xml"))
        self.export_user_list_as_xml_menu_item.setText(_translate("MainWindow", "Export As Xml"))
        self.file_ffmpeg_requirement.setText(_translate("MainWindow", "FFmpeg Requirement"))
