# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DownloaderForRedditSettingsGUI.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsGUI(object):
    def setupUi(self, SettingsGUI):
        SettingsGUI.setObjectName("SettingsGUI")
        SettingsGUI.resize(754, 880)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/settings_single_gear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SettingsGUI.setWindowIcon(icon)
        self.gridLayout_8 = QtWidgets.QGridLayout(SettingsGUI)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.stacked_widget = QtWidgets.QStackedWidget(SettingsGUI)
        self.stacked_widget.setObjectName("stacked_widget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.auto_save_checkbox = QtWidgets.QCheckBox(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.auto_save_checkbox.setFont(font)
        self.auto_save_checkbox.setObjectName("auto_save_checkbox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.auto_save_checkbox)
        self.gridLayout_9.addLayout(self.formLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.imgur_client_button = QtWidgets.QPushButton(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.imgur_client_button.setFont(font)
        self.imgur_client_button.setObjectName("imgur_client_button")
        self.verticalLayout.addWidget(self.imgur_client_button)
        self.reddit_account_link_button = QtWidgets.QPushButton(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.reddit_account_link_button.setFont(font)
        self.reddit_account_link_button.setObjectName("reddit_account_link_button")
        self.verticalLayout.addWidget(self.reddit_account_link_button)
        self.gridLayout_9.addLayout(self.verticalLayout, 0, 1, 1, 2)
        self.line = QtWidgets.QFrame(self.page)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_9.addWidget(self.line, 1, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.post_limit_label = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.post_limit_label.setFont(font)
        self.post_limit_label.setObjectName("post_limit_label")
        self.horizontalLayout.addWidget(self.post_limit_label)
        self.post_limit_spinbox = QtWidgets.QSpinBox(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.post_limit_spinbox.setFont(font)
        self.post_limit_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.post_limit_spinbox.setAccelerated(True)
        self.post_limit_spinbox.setMinimum(1)
        self.post_limit_spinbox.setMaximum(1000)
        self.post_limit_spinbox.setProperty("value", 25)
        self.post_limit_spinbox.setObjectName("post_limit_spinbox")
        self.horizontalLayout.addWidget(self.post_limit_spinbox)
        self.gridLayout_9.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        self.subreddit_sort_group = QtWidgets.QGroupBox(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subreddit_sort_group.setFont(font)
        self.subreddit_sort_group.setObjectName("subreddit_sort_group")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.subreddit_sort_group)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sub_sort_hot_radio = QtWidgets.QRadioButton(self.subreddit_sort_group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sub_sort_hot_radio.setFont(font)
        self.sub_sort_hot_radio.setObjectName("sub_sort_hot_radio")
        self.gridLayout_2.addWidget(self.sub_sort_hot_radio, 0, 0, 2, 1)
        self.sub_sort_new_radio = QtWidgets.QRadioButton(self.subreddit_sort_group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sub_sort_new_radio.setFont(font)
        self.sub_sort_new_radio.setObjectName("sub_sort_new_radio")
        self.gridLayout_2.addWidget(self.sub_sort_new_radio, 0, 1, 1, 1)
        self.sub_sort_top_radio = QtWidgets.QRadioButton(self.subreddit_sort_group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sub_sort_top_radio.setFont(font)
        self.sub_sort_top_radio.setObjectName("sub_sort_top_radio")
        self.gridLayout_2.addWidget(self.sub_sort_top_radio, 1, 1, 2, 1)
        self.sub_sort_rising_radio = QtWidgets.QRadioButton(self.subreddit_sort_group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sub_sort_rising_radio.setFont(font)
        self.sub_sort_rising_radio.setObjectName("sub_sort_rising_radio")
        self.gridLayout_2.addWidget(self.sub_sort_rising_radio, 2, 0, 1, 1)
        self.sub_sort_controversial_radio = QtWidgets.QRadioButton(self.subreddit_sort_group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sub_sort_controversial_radio.setFont(font)
        self.sub_sort_controversial_radio.setObjectName("sub_sort_controversial_radio")
        self.gridLayout_2.addWidget(self.sub_sort_controversial_radio, 3, 0, 1, 1)
        self.sub_sort_top_combo = QtWidgets.QComboBox(self.subreddit_sort_group)
        self.sub_sort_top_combo.setObjectName("sub_sort_top_combo")
        self.gridLayout_2.addWidget(self.sub_sort_top_combo, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.subreddit_sort_group, 2, 2, 2, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.post_score_combo = QtWidgets.QComboBox(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.post_score_combo.setFont(font)
        self.post_score_combo.setEditable(False)
        self.post_score_combo.setCurrentText("")
        self.post_score_combo.setObjectName("post_score_combo")
        self.gridLayout.addWidget(self.post_score_combo, 1, 0, 1, 1)
        self.post_score_limit_spin_box = QtWidgets.QSpinBox(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.post_score_limit_spin_box.setFont(font)
        self.post_score_limit_spin_box.setMaximum(100000)
        self.post_score_limit_spin_box.setObjectName("post_score_limit_spin_box")
        self.gridLayout.addWidget(self.post_score_limit_spin_box, 1, 1, 1, 1)
        self.restrict_to_score_checkbox = QtWidgets.QCheckBox(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.restrict_to_score_checkbox.setFont(font)
        self.restrict_to_score_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.restrict_to_score_checkbox.setObjectName("restrict_to_score_checkbox")
        self.gridLayout.addWidget(self.restrict_to_score_checkbox, 0, 0, 1, 2)
        self.gridLayout_9.addLayout(self.gridLayout, 3, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.date_restriction_checkbox = QtWidgets.QCheckBox(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.date_restriction_checkbox.setFont(font)
        self.date_restriction_checkbox.setObjectName("date_restriction_checkbox")
        self.gridLayout_5.addWidget(self.date_restriction_checkbox, 0, 0, 1, 1)
        self.restrict_by_custom_date_checkbox = QtWidgets.QCheckBox(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.restrict_by_custom_date_checkbox.setFont(font)
        self.restrict_by_custom_date_checkbox.setObjectName("restrict_by_custom_date_checkbox")
        self.gridLayout_5.addWidget(self.restrict_by_custom_date_checkbox, 1, 0, 1, 1)
        self.date_limit_edit = QtWidgets.QDateTimeEdit(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.date_limit_edit.setFont(font)
        self.date_limit_edit.setCalendarPopup(True)
        self.date_limit_edit.setObjectName("date_limit_edit")
        self.gridLayout_5.addWidget(self.date_limit_edit, 1, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_5, 4, 0, 1, 3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.link_filter_video_checkbox = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.link_filter_video_checkbox.setFont(font)
        self.link_filter_video_checkbox.setObjectName("link_filter_video_checkbox")
        self.gridLayout_4.addWidget(self.link_filter_video_checkbox, 0, 0, 1, 2)
        self.link_filter_image_checkbox = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.link_filter_image_checkbox.setFont(font)
        self.link_filter_image_checkbox.setObjectName("link_filter_image_checkbox")
        self.gridLayout_4.addWidget(self.link_filter_image_checkbox, 0, 2, 1, 1)
        self.link_filter_avoid_duplicates_checkbox = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.link_filter_avoid_duplicates_checkbox.setFont(font)
        self.link_filter_avoid_duplicates_checkbox.setObjectName("link_filter_avoid_duplicates_checkbox")
        self.gridLayout_4.addWidget(self.link_filter_avoid_duplicates_checkbox, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.nsfw_filter_combo = QtWidgets.QComboBox(self.groupBox_2)
        self.nsfw_filter_combo.setObjectName("nsfw_filter_combo")
        self.gridLayout_4.addWidget(self.nsfw_filter_combo, 1, 1, 1, 2)
        self.gridLayout_9.addWidget(self.groupBox_2, 5, 0, 1, 3)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.subreddit_save_location_label = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subreddit_save_location_label.setFont(font)
        self.subreddit_save_location_label.setObjectName("subreddit_save_location_label")
        self.gridLayout_6.addWidget(self.subreddit_save_location_label, 0, 0, 1, 1)
        self.subreddit_save_by_combo = QtWidgets.QComboBox(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subreddit_save_by_combo.setFont(font)
        self.subreddit_save_by_combo.setObjectName("subreddit_save_by_combo")
        self.gridLayout_6.addWidget(self.subreddit_save_by_combo, 0, 1, 1, 1)
        self.name_files_label = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_files_label.setFont(font)
        self.name_files_label.setObjectName("name_files_label")
        self.gridLayout_6.addWidget(self.name_files_label, 1, 0, 1, 1)
        self.name_downloads_by_combo = QtWidgets.QComboBox(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_downloads_by_combo.setFont(font)
        self.name_downloads_by_combo.setObjectName("name_downloads_by_combo")
        self.gridLayout_6.addWidget(self.name_downloads_by_combo, 1, 1, 1, 1)
        self.save_directory_line_edit = QtWidgets.QLineEdit(self.page)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.save_directory_line_edit.setFont(font)
        self.save_directory_line_edit.setObjectName("save_directory_line_edit")
        self.gridLayout_6.addWidget(self.save_directory_line_edit, 2, 0, 1, 1)
        self.save_directory_dialog_button = QtWidgets.QPushButton(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_directory_dialog_button.setFont(font)
        self.save_directory_dialog_button.setObjectName("save_directory_dialog_button")
        self.gridLayout_6.addWidget(self.save_directory_dialog_button, 2, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_6, 6, 0, 1, 3)
        self.line_2 = QtWidgets.QFrame(self.page)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_9.addWidget(self.line_2, 7, 0, 1, 3)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_4 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 0, 0, 1, 1)
        self.thread_limit_spinbox = QtWidgets.QSpinBox(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.thread_limit_spinbox.setFont(font)
        self.thread_limit_spinbox.setMaximum(12)
        self.thread_limit_spinbox.setProperty("value", 4)
        self.thread_limit_spinbox.setObjectName("thread_limit_spinbox")
        self.gridLayout_7.addWidget(self.thread_limit_spinbox, 0, 1, 1, 1)
        self.save_undownloaded_content_checkbox = QtWidgets.QCheckBox(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_undownloaded_content_checkbox.setFont(font)
        self.save_undownloaded_content_checkbox.setObjectName("save_undownloaded_content_checkbox")
        self.gridLayout_7.addWidget(self.save_undownloaded_content_checkbox, 1, 0, 1, 1)
        self.total_files_downloaded_label = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.total_files_downloaded_label.setFont(font)
        self.total_files_downloaded_label.setObjectName("total_files_downloaded_label")
        self.gridLayout_7.addWidget(self.total_files_downloaded_label, 2, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_7, 8, 0, 1, 3)
        self.subreddit_sort_group.raise_()
        self.line.raise_()
        self.groupBox_2.raise_()
        self.line_2.raise_()
        self.stacked_widget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tooltip_group_box = QtWidgets.QGroupBox(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tooltip_group_box.setFont(font)
        self.tooltip_group_box.setObjectName("tooltip_group_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tooltip_group_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tooltip_name_checkbox = QtWidgets.QCheckBox(self.tooltip_group_box)
        self.tooltip_name_checkbox.setObjectName("tooltip_name_checkbox")
        self.verticalLayout_2.addWidget(self.tooltip_name_checkbox)
        self.tooltip_do_not_edit_checkbox = QtWidgets.QCheckBox(self.tooltip_group_box)
        self.tooltip_do_not_edit_checkbox.setObjectName("tooltip_do_not_edit_checkbox")
        self.verticalLayout_2.addWidget(self.tooltip_do_not_edit_checkbox)
        self.tooltip_last_download_date_checkbox = QtWidgets.QCheckBox(self.tooltip_group_box)
        self.tooltip_last_download_date_checkbox.setObjectName("tooltip_last_download_date_checkbox")
        self.verticalLayout_2.addWidget(self.tooltip_last_download_date_checkbox)
        self.tooltip_custom_date_limit_checkbox = QtWidgets.QCheckBox(self.tooltip_group_box)
        self.tooltip_custom_date_limit_checkbox.setObjectName("tooltip_custom_date_limit_checkbox")
        self.verticalLayout_2.addWidget(self.tooltip_custom_date_limit_checkbox)
        self.tooltip_post_limit_checkbox = QtWidgets.QCheckBox(self.tooltip_group_box)
        self.tooltip_post_limit_checkbox.setObjectName("tooltip_post_limit_checkbox")
        self.verticalLayout_2.addWidget(self.tooltip_post_limit_checkbox)
        self.tooltip_name_downloads_by_checkbox = QtWidgets.QCheckBox(self.tooltip_group_box)
        self.tooltip_name_downloads_by_checkbox.setObjectName("tooltip_name_downloads_by_checkbox")
        self.verticalLayout_2.addWidget(self.tooltip_name_downloads_by_checkbox)
        self.tooltip_subreddit_save_by_method_checkbox = QtWidgets.QCheckBox(self.tooltip_group_box)
        self.tooltip_subreddit_save_by_method_checkbox.setObjectName("tooltip_subreddit_save_by_method_checkbox")
        self.verticalLayout_2.addWidget(self.tooltip_subreddit_save_by_method_checkbox)
        self.tooltip_save_path_checkbox = QtWidgets.QCheckBox(self.tooltip_group_box)
        self.tooltip_save_path_checkbox.setObjectName("tooltip_save_path_checkbox")
        self.verticalLayout_2.addWidget(self.tooltip_save_path_checkbox)
        self.tooltip_download_videos_checkbox = QtWidgets.QCheckBox(self.tooltip_group_box)
        self.tooltip_download_videos_checkbox.setObjectName("tooltip_download_videos_checkbox")
        self.verticalLayout_2.addWidget(self.tooltip_download_videos_checkbox)
        self.tooltip_download_images_checkbox = QtWidgets.QCheckBox(self.tooltip_group_box)
        self.tooltip_download_images_checkbox.setObjectName("tooltip_download_images_checkbox")
        self.verticalLayout_2.addWidget(self.tooltip_download_images_checkbox)
        self.tooltip_avoid_duplicates_checkbox = QtWidgets.QCheckBox(self.tooltip_group_box)
        self.tooltip_avoid_duplicates_checkbox.setObjectName("tooltip_avoid_duplicates_checkbox")
        self.verticalLayout_2.addWidget(self.tooltip_avoid_duplicates_checkbox)
        self.tooltip_nsfw_filter_checkbox = QtWidgets.QCheckBox(self.tooltip_group_box)
        self.tooltip_nsfw_filter_checkbox.setObjectName("tooltip_nsfw_filter_checkbox")
        self.verticalLayout_2.addWidget(self.tooltip_nsfw_filter_checkbox)
        self.tooltip_saved_content_count_checkbox = QtWidgets.QCheckBox(self.tooltip_group_box)
        self.tooltip_saved_content_count_checkbox.setObjectName("tooltip_saved_content_count_checkbox")
        self.verticalLayout_2.addWidget(self.tooltip_saved_content_count_checkbox)
        self.tooltip_saved_submissions_count_checkbox = QtWidgets.QCheckBox(self.tooltip_group_box)
        self.tooltip_saved_submissions_count_checkbox.setObjectName("tooltip_saved_submissions_count_checkbox")
        self.verticalLayout_2.addWidget(self.tooltip_saved_submissions_count_checkbox)
        self.tooltip_total_download_count_checkbox = QtWidgets.QCheckBox(self.tooltip_group_box)
        self.tooltip_total_download_count_checkbox.setObjectName("tooltip_total_download_count_checkbox")
        self.verticalLayout_2.addWidget(self.tooltip_total_download_count_checkbox)
        self.tooltip_added_on_date_checkbox = QtWidgets.QCheckBox(self.tooltip_group_box)
        self.tooltip_added_on_date_checkbox.setObjectName("tooltip_added_on_date_checkbox")
        self.verticalLayout_2.addWidget(self.tooltip_added_on_date_checkbox)
        self.gridLayout_10.addWidget(self.tooltip_group_box, 0, 0, 2, 1)
        self.gif_display_group_box = QtWidgets.QGroupBox(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gif_display_group_box.setFont(font)
        self.gif_display_group_box.setObjectName("gif_display_group_box")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gif_display_group_box)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gif_display_placeholder_radio = QtWidgets.QRadioButton(self.gif_display_group_box)
        self.gif_display_placeholder_radio.setObjectName("gif_display_placeholder_radio")
        self.gridLayout_11.addWidget(self.gif_display_placeholder_radio, 1, 0, 1, 1)
        self.gif_do_not_display_radio = QtWidgets.QRadioButton(self.gif_display_group_box)
        self.gif_do_not_display_radio.setObjectName("gif_do_not_display_radio")
        self.gridLayout_11.addWidget(self.gif_do_not_display_radio, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.gif_display_group_box, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem, 1, 1, 1, 1)
        self.stacked_widget.addWidget(self.page_2)
        self.gridLayout_8.addWidget(self.stacked_widget, 0, 0, 1, 3)
        self.save_cancel_button_box = QtWidgets.QDialogButtonBox(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_cancel_button_box.setFont(font)
        self.save_cancel_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.save_cancel_button_box.setCenterButtons(False)
        self.save_cancel_button_box.setObjectName("save_cancel_button_box")
        self.gridLayout_8.addWidget(self.save_cancel_button_box, 1, 2, 1, 1)
        self.restore_defaults_button = QtWidgets.QPushButton(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.restore_defaults_button.setFont(font)
        self.restore_defaults_button.setObjectName("restore_defaults_button")
        self.gridLayout_8.addWidget(self.restore_defaults_button, 1, 1, 1, 1)
        self.change_widget_button = QtWidgets.QPushButton(SettingsGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.change_widget_button.setFont(font)
        self.change_widget_button.setObjectName("change_widget_button")
        self.gridLayout_8.addWidget(self.change_widget_button, 1, 0, 1, 1)

        self.retranslateUi(SettingsGUI)
        self.stacked_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SettingsGUI)

    def retranslateUi(self, SettingsGUI):
        _translate = QtCore.QCoreApplication.translate
        SettingsGUI.setWindowTitle(_translate("SettingsGUI", "Settings"))
        self.auto_save_checkbox.setText(_translate("SettingsGUI", "Save Automatically On Close"))
        self.imgur_client_button.setText(_translate("SettingsGUI", "Imgur Client Information"))
        self.reddit_account_link_button.setText(_translate("SettingsGUI", "Link Reddit Account"))
        self.post_limit_label.setText(_translate("SettingsGUI", "Post retreival Limit (Max: 1000)"))
        self.post_limit_spinbox.setToolTip(_translate("SettingsGUI", "<html><head/><body><p><span style=\" font-size:10pt;\">Sets the max number of posts to retrieve from Reddit.  The limit is 1000 posts (this limit is imposed by the reddit api)</span></p></body></html>"))
        self.subreddit_sort_group.setTitle(_translate("SettingsGUI", "Subreddit Sort Type"))
        self.sub_sort_hot_radio.setText(_translate("SettingsGUI", "Hot"))
        self.sub_sort_new_radio.setText(_translate("SettingsGUI", "New"))
        self.sub_sort_top_radio.setText(_translate("SettingsGUI", "Top"))
        self.sub_sort_rising_radio.setText(_translate("SettingsGUI", "Rising"))
        self.sub_sort_controversial_radio.setText(_translate("SettingsGUI", "Controversial"))
        self.restrict_to_score_checkbox.setToolTip(_translate("SettingsGUI", "<html><head/><body><p><span style=\" font-size:10pt;\">If checked, posts will only be downloaded if they are above or below a certain score</span></p></body></html>"))
        self.restrict_to_score_checkbox.setText(_translate("SettingsGUI", "Restrict Download By Score"))
        self.date_restriction_checkbox.setToolTip(_translate("SettingsGUI", "<html><head/><body><p><span style=\" font-size:10pt;\">If checked, only links that have been posted after the date of the last post downloaded by each user will be downloaded.</span></p></body></html>"))
        self.date_restriction_checkbox.setText(_translate("SettingsGUI", "Inforce User Date Limits"))
        self.restrict_by_custom_date_checkbox.setText(_translate("SettingsGUI", "Restrict downloads by cusom date:"))
        self.date_limit_edit.setDisplayFormat(_translate("SettingsGUI", "M/d/yyyy hh:mm ap"))
        self.groupBox_2.setTitle(_translate("SettingsGUI", "Content Filters"))
        self.link_filter_video_checkbox.setText(_translate("SettingsGUI", "Download Videos"))
        self.link_filter_image_checkbox.setText(_translate("SettingsGUI", "Download Images"))
        self.link_filter_avoid_duplicates_checkbox.setText(_translate("SettingsGUI", "Avoid Duplicates"))
        self.label_3.setText(_translate("SettingsGUI", "NSFW filter:"))
        self.subreddit_save_location_label.setText(_translate("SettingsGUI", "Subreddits save to folder designated by:"))
        self.name_files_label.setText(_translate("SettingsGUI", "Name downloaded files by:"))
        self.save_directory_dialog_button.setText(_translate("SettingsGUI", "Select Save Directory"))
        self.label_4.setText(_translate("SettingsGUI", "Number of simultaneous download threads:"))
        self.thread_limit_spinbox.setToolTip(_translate("SettingsGUI", "<html><head/><body><p><span style=\" font-size:10pt;\">This is the number of download threads that will be spawned to download content simultaneously.  The max number is set based on your computers number of processor cores (real and logical)</span></p></body></html>"))
        self.save_undownloaded_content_checkbox.setToolTip(_translate("SettingsGUI", "<html><head/><body><p>When checked, content that has been extracted but not downloaded will be saved and redownloaded during the next run. This prevents content from having to be extracted more than once</p></body></html>"))
        self.save_undownloaded_content_checkbox.setText(_translate("SettingsGUI", "Save undownloaded content"))
        self.total_files_downloaded_label.setText(_translate("SettingsGUI", "Total Files Downloaded: 0"))
        self.tooltip_group_box.setToolTip(_translate("SettingsGUI", "<html><head/><body><p>Choose which reddit object attributes are displayed via tooltip when hovering over reddit objects in the main window.</p></body></html>"))
        self.tooltip_group_box.setTitle(_translate("SettingsGUI", "Tooltip Display Options"))
        self.tooltip_name_checkbox.setText(_translate("SettingsGUI", "Name"))
        self.tooltip_do_not_edit_checkbox.setText(_translate("SettingsGUI", "Do Not Edit"))
        self.tooltip_last_download_date_checkbox.setText(_translate("SettingsGUI", "Last Content Download Date"))
        self.tooltip_custom_date_limit_checkbox.setText(_translate("SettingsGUI", "Custom Date Limit"))
        self.tooltip_post_limit_checkbox.setText(_translate("SettingsGUI", "Post Limit"))
        self.tooltip_name_downloads_by_checkbox.setText(_translate("SettingsGUI", "Name Downloads By"))
        self.tooltip_subreddit_save_by_method_checkbox.setText(_translate("SettingsGUI", "Subreddit Save By Method"))
        self.tooltip_save_path_checkbox.setText(_translate("SettingsGUI", "Save Path"))
        self.tooltip_download_videos_checkbox.setText(_translate("SettingsGUI", "Download Videos"))
        self.tooltip_download_images_checkbox.setText(_translate("SettingsGUI", "Download Images"))
        self.tooltip_avoid_duplicates_checkbox.setText(_translate("SettingsGUI", "Avoid Duplicates"))
        self.tooltip_nsfw_filter_checkbox.setText(_translate("SettingsGUI", "NSFW Filter"))
        self.tooltip_saved_content_count_checkbox.setText(_translate("SettingsGUI", "Saved Content"))
        self.tooltip_saved_submissions_count_checkbox.setText(_translate("SettingsGUI", "Saved Submissions"))
        self.tooltip_total_download_count_checkbox.setText(_translate("SettingsGUI", "Total Download Count"))
        self.tooltip_added_on_date_checkbox.setText(_translate("SettingsGUI", "Added On Date"))
        self.gif_display_group_box.setTitle(_translate("SettingsGUI", "Gif Display Options"))
        self.gif_display_placeholder_radio.setText(_translate("SettingsGUI", "Display Placeholder"))
        self.gif_do_not_display_radio.setText(_translate("SettingsGUI", "Do Not Display Gifs"))
        self.restore_defaults_button.setText(_translate("SettingsGUI", "Restore Defaults"))
        self.change_widget_button.setText(_translate("SettingsGUI", "Display Settings"))

