# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RedditObjectSettingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RedditObjectSettingsDialog(object):
    def setupUi(self, RedditObjectSettingsDialog):
        RedditObjectSettingsDialog.setObjectName("RedditObjectSettingsDialog")
        RedditObjectSettingsDialog.resize(727, 1239)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(RedditObjectSettingsDialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(RedditObjectSettingsDialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.reddit_objects_list_view = QtWidgets.QListView(self.splitter)
        self.reddit_objects_list_view.setObjectName("reddit_objects_list_view")
        self.layoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lock_settings_checkbox = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.lock_settings_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lock_settings_checkbox.setObjectName("lock_settings_checkbox")
        self.gridLayout_3.addWidget(self.lock_settings_checkbox, 1, 0, 1, 1)
        self.download_button = QtWidgets.QPushButton(self.layoutWidget_2)
        self.download_button.setObjectName("download_button")
        self.gridLayout_3.addWidget(self.download_button, 0, 0, 1, 1)
        self.enable_download_checkbox = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.enable_download_checkbox.setObjectName("enable_download_checkbox")
        self.gridLayout_3.addWidget(self.enable_download_checkbox, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.info_form = QtWidgets.QFormLayout()
        self.info_form.setObjectName("info_form")
        self.label = QtWidgets.QLabel(self.layoutWidget_2)
        self.label.setObjectName("label")
        self.info_form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.info_form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.info_form.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.info_form.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.info_form.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.name_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.name_label.setObjectName("name_label")
        self.info_form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.name_label)
        self.id_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.id_label.setObjectName("id_label")
        self.info_form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.id_label)
        self.date_created_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.date_created_label.setObjectName("date_created_label")
        self.info_form.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.date_created_label)
        self.date_added_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.date_added_label.setObjectName("date_added_label")
        self.info_form.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.date_added_label)
        self.last_download_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.last_download_label.setObjectName("last_download_label")
        self.info_form.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.last_download_label)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.info_form.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_27)
        self.verticalLayout.addLayout(self.info_form)
        self.line = QtWidgets.QFrame(self.layoutWidget_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.download_info_form = QtWidgets.QFormLayout()
        self.download_info_form.setObjectName("download_info_form")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.download_info_form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.post_count_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.post_count_label.setObjectName("post_count_label")
        self.download_info_form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.post_count_label)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.download_info_form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.comment_count_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.comment_count_label.setObjectName("comment_count_label")
        self.download_info_form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comment_count_label)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.download_info_form.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.content_count_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.content_count_label.setObjectName("content_count_label")
        self.download_info_form.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.content_count_label)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.download_info_form.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_26)
        self.verticalLayout.addLayout(self.download_info_form)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.post_download_form = QtWidgets.QFormLayout()
        self.post_download_form.setObjectName("post_download_form")
        self.line_2 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.post_download_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.line_2)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.post_download_form.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.label_19)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.post_download_form.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.post_limit_spinbox = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.post_limit_spinbox.setMaximum(1000)
        self.post_limit_spinbox.setObjectName("post_limit_spinbox")
        self.horizontalLayout_3.addWidget(self.post_limit_spinbox)
        self.post_limit_max_button = QtWidgets.QToolButton(self.layoutWidget_2)
        self.post_limit_max_button.setObjectName("post_limit_max_button")
        self.horizontalLayout_3.addWidget(self.post_limit_max_button)
        self.post_download_form.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.post_download_form.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.score_limit_spinbox = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.score_limit_spinbox.setMaximum(10000000)
        self.score_limit_spinbox.setObjectName("score_limit_spinbox")
        self.post_download_form.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.score_limit_spinbox)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.post_download_form.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.score_limit_operator_combo = QtWidgets.QComboBox(self.layoutWidget_2)
        self.score_limit_operator_combo.setObjectName("score_limit_operator_combo")
        self.post_download_form.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.score_limit_operator_combo)
        self.date_limit_checkbox = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.date_limit_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.date_limit_checkbox.setObjectName("date_limit_checkbox")
        self.post_download_form.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.date_limit_checkbox)
        self.date_limit_edit = QtWidgets.QDateTimeEdit(self.layoutWidget_2)
        self.date_limit_edit.setDateTime(QtCore.QDateTime(QtCore.QDate(2005, 6, 23), QtCore.QTime(14, 43, 53)))
        self.date_limit_edit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2005, 6, 23), QtCore.QTime(14, 43, 53)))
        self.date_limit_edit.setObjectName("date_limit_edit")
        self.post_download_form.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.date_limit_edit)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.post_download_form.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.avoid_duplicates_checkbox = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.avoid_duplicates_checkbox.setText("")
        self.avoid_duplicates_checkbox.setObjectName("avoid_duplicates_checkbox")
        self.post_download_form.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.avoid_duplicates_checkbox)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.post_download_form.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.download_videos_checkbox = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.download_videos_checkbox.setText("")
        self.download_videos_checkbox.setObjectName("download_videos_checkbox")
        self.post_download_form.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.download_videos_checkbox)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.post_download_form.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.download_images_checkbox = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.download_images_checkbox.setText("")
        self.download_images_checkbox.setObjectName("download_images_checkbox")
        self.post_download_form.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.download_images_checkbox)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_29.setObjectName("label_29")
        self.post_download_form.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.download_gifs_checkbox = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.download_gifs_checkbox.setText("")
        self.download_gifs_checkbox.setObjectName("download_gifs_checkbox")
        self.post_download_form.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.download_gifs_checkbox)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_28.setObjectName("label_28")
        self.post_download_form.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.nsfw_filter_combo = QtWidgets.QComboBox(self.layoutWidget_2)
        self.nsfw_filter_combo.setObjectName("nsfw_filter_combo")
        self.post_download_form.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.nsfw_filter_combo)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.post_download_form.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.post_sort_combo = QtWidgets.QComboBox(self.layoutWidget_2)
        self.post_sort_combo.setObjectName("post_sort_combo")
        self.post_download_form.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.post_sort_combo)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.post_download_form.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.download_naming_combo = QtWidgets.QComboBox(self.layoutWidget_2)
        self.download_naming_combo.setObjectName("download_naming_combo")
        self.post_download_form.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.download_naming_combo)
        self.subreddit_save_structure_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.subreddit_save_structure_label.setObjectName("subreddit_save_structure_label")
        self.post_download_form.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.subreddit_save_structure_label)
        self.subreddit_save_structure_combo = QtWidgets.QComboBox(self.layoutWidget_2)
        self.subreddit_save_structure_combo.setObjectName("subreddit_save_structure_combo")
        self.post_download_form.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.subreddit_save_structure_combo)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.post_download_form.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_30.setObjectName("label_30")
        self.post_download_form.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.download_self_posts_checkbox = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.download_self_posts_checkbox.setText("")
        self.download_self_posts_checkbox.setObjectName("download_self_posts_checkbox")
        self.post_download_form.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.download_self_posts_checkbox)
        self.extract_self_post_content_checkbox = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.extract_self_post_content_checkbox.setText("")
        self.extract_self_post_content_checkbox.setObjectName("extract_self_post_content_checkbox")
        self.post_download_form.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.extract_self_post_content_checkbox)
        self.verticalLayout.addLayout(self.post_download_form)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.comment_download_form = QtWidgets.QFormLayout()
        self.comment_download_form.setObjectName("comment_download_form")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.comment_download_form.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_20)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.comment_download_form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.comment_download_combo = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comment_download_combo.setObjectName("comment_download_combo")
        self.comment_download_form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comment_download_combo)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.comment_download_form.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.comment_content_download_combo = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comment_content_download_combo.setObjectName("comment_content_download_combo")
        self.comment_download_form.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comment_content_download_combo)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_23.setObjectName("label_23")
        self.comment_download_form.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_24.setObjectName("label_24")
        self.comment_download_form.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.comment_score_limit_spinbox = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.comment_score_limit_spinbox.setMaximum(10000000)
        self.comment_score_limit_spinbox.setObjectName("comment_score_limit_spinbox")
        self.comment_download_form.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comment_score_limit_spinbox)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.comment_download_form.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.comment_score_operator_combo = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comment_score_operator_combo.setObjectName("comment_score_operator_combo")
        self.comment_download_form.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comment_score_operator_combo)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.comment_download_form.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.comment_sort_combo = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comment_sort_combo.setObjectName("comment_sort_combo")
        self.comment_download_form.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.comment_sort_combo)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comment_limit_spinbox = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.comment_limit_spinbox.setMaximum(10000)
        self.comment_limit_spinbox.setObjectName("comment_limit_spinbox")
        self.horizontalLayout_4.addWidget(self.comment_limit_spinbox)
        self.comment_limit_max_button = QtWidgets.QToolButton(self.layoutWidget_2)
        self.comment_limit_max_button.setObjectName("comment_limit_max_button")
        self.horizontalLayout_4.addWidget(self.comment_limit_max_button)
        self.comment_download_form.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.comment_download_form)
        self.verticalLayout_2.addWidget(self.splitter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.reset_button = QtWidgets.QPushButton(RedditObjectSettingsDialog)
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout.addWidget(self.reset_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.dialog_button_box = QtWidgets.QDialogButtonBox(RedditObjectSettingsDialog)
        self.dialog_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.dialog_button_box.setCenterButtons(False)
        self.dialog_button_box.setObjectName("dialog_button_box")
        self.horizontalLayout.addWidget(self.dialog_button_box)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(RedditObjectSettingsDialog)
        QtCore.QMetaObject.connectSlotsByName(RedditObjectSettingsDialog)

    def retranslateUi(self, RedditObjectSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        RedditObjectSettingsDialog.setWindowTitle(_translate("RedditObjectSettingsDialog", "Settings"))
        self.lock_settings_checkbox.setToolTip(_translate("RedditObjectSettingsDialog", "When checked, the settings in this window will not be overwritten due to changes in the main settings window"))
        self.lock_settings_checkbox.setText(_translate("RedditObjectSettingsDialog", "Lock Settings"))
        self.download_button.setText(_translate("RedditObjectSettingsDialog", "Download "))
        self.enable_download_checkbox.setText(_translate("RedditObjectSettingsDialog", "Download Enabled"))
        self.label.setText(_translate("RedditObjectSettingsDialog", "Name:"))
        self.label_2.setText(_translate("RedditObjectSettingsDialog", "Id:"))
        self.label_3.setText(_translate("RedditObjectSettingsDialog", "Date Created:"))
        self.label_4.setText(_translate("RedditObjectSettingsDialog", "Date Added:"))
        self.label_5.setText(_translate("RedditObjectSettingsDialog", "Last Download:"))
        self.name_label.setText(_translate("RedditObjectSettingsDialog", "name"))
        self.id_label.setText(_translate("RedditObjectSettingsDialog", "0"))
        self.date_created_label.setText(_translate("RedditObjectSettingsDialog", "date_created"))
        self.date_added_label.setText(_translate("RedditObjectSettingsDialog", "date_added"))
        self.last_download_label.setText(_translate("RedditObjectSettingsDialog", "last_download"))
        self.label_27.setText(_translate("RedditObjectSettingsDialog", "Basic Info"))
        self.label_6.setText(_translate("RedditObjectSettingsDialog", "Post Count:"))
        self.post_count_label.setText(_translate("RedditObjectSettingsDialog", "post_count"))
        self.label_8.setText(_translate("RedditObjectSettingsDialog", "Comment Count:"))
        self.comment_count_label.setText(_translate("RedditObjectSettingsDialog", "comment_count"))
        self.label_10.setText(_translate("RedditObjectSettingsDialog", "Content Count:"))
        self.content_count_label.setText(_translate("RedditObjectSettingsDialog", "content_count"))
        self.label_26.setText(_translate("RedditObjectSettingsDialog", "Download Info"))
        self.label_19.setText(_translate("RedditObjectSettingsDialog", "Post Download Settings"))
        self.label_7.setText(_translate("RedditObjectSettingsDialog", "Post Limit:"))
        self.post_limit_max_button.setText(_translate("RedditObjectSettingsDialog", "Max"))
        self.label_9.setText(_translate("RedditObjectSettingsDialog", "Score Limit:"))
        self.label_11.setText(_translate("RedditObjectSettingsDialog", "Score Limit Eval:"))
        self.date_limit_checkbox.setText(_translate("RedditObjectSettingsDialog", "Date Limit:    "))
        self.label_12.setText(_translate("RedditObjectSettingsDialog", "Avoid Duplicates:"))
        self.label_13.setText(_translate("RedditObjectSettingsDialog", "Download Videos:"))
        self.label_14.setText(_translate("RedditObjectSettingsDialog", "Download Images:"))
        self.label_29.setText(_translate("RedditObjectSettingsDialog", "Download Gifs:"))
        self.label_28.setText(_translate("RedditObjectSettingsDialog", "NSFW Filter:"))
        self.label_16.setText(_translate("RedditObjectSettingsDialog", "Sort Posts By:"))
        self.label_17.setText(_translate("RedditObjectSettingsDialog", "Download Naming:"))
        self.subreddit_save_structure_label.setText(_translate("RedditObjectSettingsDialog", "Subreddit Path Scheme:"))
        self.label_15.setText(_translate("RedditObjectSettingsDialog", "Download Self Posts:"))
        self.label_30.setText(_translate("RedditObjectSettingsDialog", "Extract Self Post Content:"))
        self.label_20.setText(_translate("RedditObjectSettingsDialog", "Comment Download Settings"))
        self.label_22.setText(_translate("RedditObjectSettingsDialog", "Download:"))
        self.label_21.setText(_translate("RedditObjectSettingsDialog", "Download Links"))
        self.label_23.setText(_translate("RedditObjectSettingsDialog", "Comment Limit:"))
        self.label_24.setText(_translate("RedditObjectSettingsDialog", "Score Limit:"))
        self.label_25.setText(_translate("RedditObjectSettingsDialog", "Score Limit Eval:"))
        self.label_18.setText(_translate("RedditObjectSettingsDialog", "Sort Comments By:"))
        self.comment_limit_max_button.setText(_translate("RedditObjectSettingsDialog", "Max"))
        self.reset_button.setText(_translate("RedditObjectSettingsDialog", "Reset"))

