# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserFinderSettingsGUI.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UserFinderSettingsGUI(object):
    def setupUi(self, UserFinderSettingsGUI):
        UserFinderSettingsGUI.setObjectName("UserFinderSettingsGUI")
        UserFinderSettingsGUI.resize(615, 694)
        font = QtGui.QFont()
        font.setPointSize(10)
        UserFinderSettingsGUI.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Images/settings_single_gear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UserFinderSettingsGUI.setWindowIcon(icon)
        self.gridLayout_5 = QtWidgets.QGridLayout(UserFinderSettingsGUI)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.autorun_group_box = QtWidgets.QGroupBox(UserFinderSettingsGUI)
        self.autorun_group_box.setObjectName("autorun_group_box")
        self.gridLayout = QtWidgets.QGridLayout(self.autorun_group_box)
        self.gridLayout.setObjectName("gridLayout")
        self.run_with_main_checkbox = QtWidgets.QCheckBox(self.autorun_group_box)
        self.run_with_main_checkbox.setObjectName("run_with_main_checkbox")
        self.gridLayout.addWidget(self.run_with_main_checkbox, 0, 0, 1, 1)
        self.auto_add_checkbox = QtWidgets.QCheckBox(self.autorun_group_box)
        self.auto_add_checkbox.setObjectName("auto_add_checkbox")
        self.gridLayout.addWidget(self.auto_add_checkbox, 1, 0, 1, 1)
        self.silent_run_checkbox = QtWidgets.QCheckBox(self.autorun_group_box)
        self.silent_run_checkbox.setObjectName("silent_run_checkbox")
        self.gridLayout.addWidget(self.silent_run_checkbox, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.autorun_group_box)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.auto_add_user_list_combo = QtWidgets.QComboBox(self.autorun_group_box)
        self.auto_add_user_list_combo.setObjectName("auto_add_user_list_combo")
        self.gridLayout.addWidget(self.auto_add_user_list_combo, 4, 0, 1, 1)
        self.gridLayout_5.addWidget(self.autorun_group_box, 0, 0, 1, 1)
        self.content_double_click_group_box = QtWidgets.QGroupBox(UserFinderSettingsGUI)
        self.content_double_click_group_box.setObjectName("content_double_click_group_box")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.content_double_click_group_box)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.open_link_in_dialog_radio = QtWidgets.QRadioButton(self.content_double_click_group_box)
        self.open_link_in_dialog_radio.setObjectName("open_link_in_dialog_radio")
        self.gridLayout_3.addWidget(self.open_link_in_dialog_radio, 0, 0, 1, 1)
        self.open_link_in_browser_radio = QtWidgets.QRadioButton(self.content_double_click_group_box)
        self.open_link_in_browser_radio.setObjectName("open_link_in_browser_radio")
        self.gridLayout_3.addWidget(self.open_link_in_browser_radio, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.content_double_click_group_box, 1, 0, 1, 1)
        self.found_user_options_group_box = QtWidgets.QGroupBox(UserFinderSettingsGUI)
        self.found_user_options_group_box.setObjectName("found_user_options_group_box")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.found_user_options_group_box)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.show_reddit_page_checkbox = QtWidgets.QCheckBox(self.found_user_options_group_box)
        self.show_reddit_page_checkbox.setObjectName("show_reddit_page_checkbox")
        self.gridLayout_2.addWidget(self.show_reddit_page_checkbox, 0, 0, 1, 1)
        self.sample_size_spinbox = QtWidgets.QSpinBox(self.found_user_options_group_box)
        self.sample_size_spinbox.setObjectName("sample_size_spinbox")
        self.gridLayout_2.addWidget(self.sample_size_spinbox, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.found_user_options_group_box)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.user_new_radio = QtWidgets.QRadioButton(self.found_user_options_group_box)
        self.user_new_radio.setObjectName("user_new_radio")
        self.gridLayout_2.addWidget(self.user_new_radio, 4, 0, 1, 1)
        self.user_top_radio = QtWidgets.QRadioButton(self.found_user_options_group_box)
        self.user_top_radio.setObjectName("user_top_radio")
        self.gridLayout_2.addWidget(self.user_top_radio, 3, 0, 1, 1)
        self.user_selected_new_radio = QtWidgets.QRadioButton(self.found_user_options_group_box)
        self.user_selected_new_radio.setObjectName("user_selected_new_radio")
        self.gridLayout_2.addWidget(self.user_selected_new_radio, 8, 0, 1, 1)
        self.user_selected_only_radio = QtWidgets.QRadioButton(self.found_user_options_group_box)
        self.user_selected_only_radio.setObjectName("user_selected_only_radio")
        self.gridLayout_2.addWidget(self.user_selected_only_radio, 6, 0, 1, 1)
        self.user_selected_top_radio = QtWidgets.QRadioButton(self.found_user_options_group_box)
        self.user_selected_top_radio.setObjectName("user_selected_top_radio")
        self.gridLayout_2.addWidget(self.user_selected_top_radio, 7, 0, 1, 1)
        self.gridLayout_5.addWidget(self.found_user_options_group_box, 0, 1, 2, 1)
        self.content_size_options_group_box = QtWidgets.QGroupBox(UserFinderSettingsGUI)
        self.content_size_options_group_box.setObjectName("content_size_options_group_box")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.content_size_options_group_box)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.content_extra_small_radio = QtWidgets.QRadioButton(self.content_size_options_group_box)
        self.content_extra_small_radio.setObjectName("content_extra_small_radio")
        self.gridLayout_4.addWidget(self.content_extra_small_radio, 0, 0, 1, 1)
        self.content_small_radio = QtWidgets.QRadioButton(self.content_size_options_group_box)
        self.content_small_radio.setObjectName("content_small_radio")
        self.gridLayout_4.addWidget(self.content_small_radio, 1, 0, 1, 1)
        self.content_medium_radio = QtWidgets.QRadioButton(self.content_size_options_group_box)
        self.content_medium_radio.setObjectName("content_medium_radio")
        self.gridLayout_4.addWidget(self.content_medium_radio, 2, 0, 1, 1)
        self.content_large_radio = QtWidgets.QRadioButton(self.content_size_options_group_box)
        self.content_large_radio.setObjectName("content_large_radio")
        self.gridLayout_4.addWidget(self.content_large_radio, 3, 0, 1, 1)
        self.content_original_size_radio = QtWidgets.QRadioButton(self.content_size_options_group_box)
        self.content_original_size_radio.setObjectName("content_original_size_radio")
        self.gridLayout_4.addWidget(self.content_original_size_radio, 5, 0, 1, 1)
        self.content_extra_large_radio = QtWidgets.QRadioButton(self.content_size_options_group_box)
        self.content_extra_large_radio.setObjectName("content_extra_large_radio")
        self.gridLayout_4.addWidget(self.content_extra_large_radio, 4, 0, 1, 1)
        self.gridLayout_5.addWidget(self.content_size_options_group_box, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 2, 1, 2, 1)
        self.button_box = QtWidgets.QDialogButtonBox(UserFinderSettingsGUI)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.button_box.setObjectName("button_box")
        self.gridLayout_5.addWidget(self.button_box, 4, 1, 1, 1)

        self.retranslateUi(UserFinderSettingsGUI)
        QtCore.QMetaObject.connectSlotsByName(UserFinderSettingsGUI)

    def retranslateUi(self, UserFinderSettingsGUI):
        _translate = QtCore.QCoreApplication.translate
        UserFinderSettingsGUI.setWindowTitle(_translate("UserFinderSettingsGUI", "User Finder Settings"))
        UserFinderSettingsGUI.setWhatsThis(_translate("UserFinderSettingsGUI", "Settings for the user finder"))
        self.autorun_group_box.setTitle(_translate("UserFinderSettingsGUI", "Auto-Run Options"))
        self.run_with_main_checkbox.setText(_translate("UserFinderSettingsGUI", "Run With Main Downloader"))
        self.auto_add_checkbox.setText(_translate("UserFinderSettingsGUI", "Auto Add Found Users"))
        self.silent_run_checkbox.setText(_translate("UserFinderSettingsGUI", "Auto Run Silently"))
        self.label_4.setText(_translate("UserFinderSettingsGUI", "Auto Add User List:"))
        self.content_double_click_group_box.setTitle(_translate("UserFinderSettingsGUI", "Content Double Click Options"))
        self.open_link_in_dialog_radio.setText(_translate("UserFinderSettingsGUI", "Open Link In Dialog"))
        self.open_link_in_browser_radio.setText(_translate("UserFinderSettingsGUI", "Open Link In Browser"))
        self.found_user_options_group_box.setTitle(_translate("UserFinderSettingsGUI", "Found User Options"))
        self.show_reddit_page_checkbox.setToolTip(_translate("UserFinderSettingsGUI", "When selected the users reddit page will be displayed instead of samples of links"))
        self.show_reddit_page_checkbox.setText(_translate("UserFinderSettingsGUI", "Show Users Reddit Page"))
        self.label.setText(_translate("UserFinderSettingsGUI", "Number of Samples"))
        self.user_new_radio.setToolTip(_translate("UserFinderSettingsGUI", "Displayed posts will be sorted by new"))
        self.user_new_radio.setText(_translate("UserFinderSettingsGUI", "Users Newest Posts"))
        self.user_top_radio.setToolTip(_translate("UserFinderSettingsGUI", "Displayed posts will be sorted by top"))
        self.user_top_radio.setText(_translate("UserFinderSettingsGUI", "Users Top Posts"))
        self.user_selected_new_radio.setToolTip(_translate("UserFinderSettingsGUI", "<html><head/><body><p>When selected the posts that earned the user a spot in the found users list will be displayed first followed by the selected number of the usrers new posts.</p></body></html>"))
        self.user_selected_new_radio.setText(_translate("UserFinderSettingsGUI", "Selected Posts\n"
"Followed By New"))
        self.user_selected_only_radio.setToolTip(_translate("UserFinderSettingsGUI", "Will provide samples of only the posts that were in the top for the selected subreddits.  Sample size will be ignored."))
        self.user_selected_only_radio.setText(_translate("UserFinderSettingsGUI", "Selected Posts Only"))
        self.user_selected_top_radio.setToolTip(_translate("UserFinderSettingsGUI", "When selected the posts that earned the user a spot in the found users list will be displayed first followed by the selected number of the usrers top posts."))
        self.user_selected_top_radio.setText(_translate("UserFinderSettingsGUI", "Selected Posts\n"
"Followed By Top"))
        self.content_size_options_group_box.setTitle(_translate("UserFinderSettingsGUI", "Content Size:"))
        self.content_extra_small_radio.setToolTip(_translate("UserFinderSettingsGUI", "48 px"))
        self.content_extra_small_radio.setText(_translate("UserFinderSettingsGUI", "Extra Small"))
        self.content_small_radio.setToolTip(_translate("UserFinderSettingsGUI", "72 px"))
        self.content_small_radio.setText(_translate("UserFinderSettingsGUI", "Small"))
        self.content_medium_radio.setToolTip(_translate("UserFinderSettingsGUI", "110 px"))
        self.content_medium_radio.setText(_translate("UserFinderSettingsGUI", "Medium"))
        self.content_large_radio.setToolTip(_translate("UserFinderSettingsGUI", "176 px"))
        self.content_large_radio.setText(_translate("UserFinderSettingsGUI", "Large"))
        self.content_original_size_radio.setToolTip(_translate("UserFinderSettingsGUI", "Original Content Size"))
        self.content_original_size_radio.setText(_translate("UserFinderSettingsGUI", "Original Size"))
        self.content_extra_large_radio.setToolTip(_translate("UserFinderSettingsGUI", "256 px"))
        self.content_extra_large_radio.setText(_translate("UserFinderSettingsGUI", "Extra Large"))

