# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserFinderGUI.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UserFinderGUI(object):
    def setupUi(self, UserFinderGUI):
        UserFinderGUI.setObjectName("UserFinderGUI")
        UserFinderGUI.resize(890, 865)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Images/RedditDownloaderIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UserFinderGUI.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(UserFinderGUI)
        self.gridLayout.setObjectName("gridLayout")
        self.progress_bar = QtWidgets.QProgressBar(UserFinderGUI)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setInvertedAppearance(False)
        self.progress_bar.setObjectName("progress_bar")
        self.gridLayout.addWidget(self.progress_bar, 1, 0, 1, 1)
        self.progress_label = QtWidgets.QLabel(UserFinderGUI)
        self.progress_label.setObjectName("progress_label")
        self.gridLayout.addWidget(self.progress_label, 1, 1, 1, 1)
        self.stacked_widget = QtWidgets.QStackedWidget(UserFinderGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stacked_widget.setFont(font)
        self.stacked_widget.setObjectName("stacked_widget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 1, 2, 1, 1)
        self.view_users_button = QtWidgets.QPushButton(self.page)
        self.view_users_button.setObjectName("view_users_button")
        self.gridLayout_6.addWidget(self.view_users_button, 1, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.page)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.remove_subreddit_button = QtWidgets.QToolButton(self.layoutWidget)
        self.remove_subreddit_button.setObjectName("remove_subreddit_button")
        self.gridLayout_4.addWidget(self.remove_subreddit_button, 2, 2, 1, 1)
        self.add_subreddit_button = QtWidgets.QToolButton(self.layoutWidget)
        self.add_subreddit_button.setObjectName("add_subreddit_button")
        self.gridLayout_4.addWidget(self.add_subreddit_button, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.subreddit_watchlist_widget = QtWidgets.QListWidget(self.layoutWidget)
        self.subreddit_watchlist_widget.setObjectName("subreddit_watchlist_widget")
        self.gridLayout_4.addWidget(self.subreddit_watchlist_widget, 1, 0, 1, 3)
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.remove_user_button = QtWidgets.QToolButton(self.widget)
        self.remove_user_button.setObjectName("remove_user_button")
        self.gridLayout_3.addWidget(self.remove_user_button, 2, 2, 1, 1)
        self.add_user_button = QtWidgets.QToolButton(self.widget)
        self.add_user_button.setObjectName("add_user_button")
        self.gridLayout_3.addWidget(self.add_user_button, 2, 1, 1, 1)
        self.user_blacklist_widget = QtWidgets.QListWidget(self.widget)
        self.user_blacklist_widget.setObjectName("user_blacklist_widget")
        self.gridLayout_3.addWidget(self.user_blacklist_widget, 1, 0, 1, 3)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.score_limit_spinbox = QtWidgets.QSpinBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.score_limit_spinbox.setFont(font)
        self.score_limit_spinbox.setObjectName("score_limit_spinbox")
        self.gridLayout_2.addWidget(self.score_limit_spinbox, 2, 1, 1, 1)
        self.filter_by_score_checkbox = QtWidgets.QCheckBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.filter_by_score_checkbox.setFont(font)
        self.filter_by_score_checkbox.setObjectName("filter_by_score_checkbox")
        self.gridLayout_2.addWidget(self.filter_by_score_checkbox, 2, 0, 1, 1)
        self.post_limit_spinbox = QtWidgets.QSpinBox(self.widget1)
        self.post_limit_spinbox.setObjectName("post_limit_spinbox")
        self.gridLayout_2.addWidget(self.post_limit_spinbox, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.top_sort_group_box = QtWidgets.QGroupBox(self.widget1)
        self.top_sort_group_box.setObjectName("top_sort_group_box")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.top_sort_group_box)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.hour_radio = QtWidgets.QRadioButton(self.top_sort_group_box)
        self.hour_radio.setObjectName("hour_radio")
        self.gridLayout_5.addWidget(self.hour_radio, 0, 0, 1, 1)
        self.day_radio = QtWidgets.QRadioButton(self.top_sort_group_box)
        self.day_radio.setObjectName("day_radio")
        self.gridLayout_5.addWidget(self.day_radio, 1, 0, 1, 1)
        self.week_radio = QtWidgets.QRadioButton(self.top_sort_group_box)
        self.week_radio.setObjectName("week_radio")
        self.gridLayout_5.addWidget(self.week_radio, 2, 0, 1, 1)
        self.month_radio = QtWidgets.QRadioButton(self.top_sort_group_box)
        self.month_radio.setObjectName("month_radio")
        self.gridLayout_5.addWidget(self.month_radio, 3, 0, 1, 1)
        self.year_radio = QtWidgets.QRadioButton(self.top_sort_group_box)
        self.year_radio.setObjectName("year_radio")
        self.gridLayout_5.addWidget(self.year_radio, 4, 0, 1, 1)
        self.all_time_radio = QtWidgets.QRadioButton(self.top_sort_group_box)
        self.all_time_radio.setObjectName("all_time_radio")
        self.gridLayout_5.addWidget(self.all_time_radio, 5, 0, 1, 1)
        self.gridLayout_2.addWidget(self.top_sort_group_box, 0, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.splitter, 0, 0, 1, 4)
        self.run_button = QtWidgets.QPushButton(self.page)
        self.run_button.setObjectName("run_button")
        self.gridLayout_6.addWidget(self.run_button, 1, 3, 1, 1)
        self.settings_button = QtWidgets.QPushButton(self.page)
        self.settings_button.setObjectName("settings_button")
        self.gridLayout_6.addWidget(self.settings_button, 1, 1, 1, 1)
        self.stacked_widget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.user_finder_button = QtWidgets.QPushButton(self.page_2)
        self.user_finder_button.setObjectName("user_finder_button")
        self.gridLayout_13.addWidget(self.user_finder_button, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem2, 1, 1, 1, 1)
        self.splitter_three = QtWidgets.QSplitter(self.page_2)
        self.splitter_three.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_three.setObjectName("splitter_three")
        self.user_list_view = QtWidgets.QListView(self.splitter_three)
        self.user_list_view.setObjectName("user_list_view")
        self.content_list_widget = QtWidgets.QListWidget(self.splitter_three)
        self.content_list_widget.setObjectName("content_list_widget")
        self.gridLayout_13.addWidget(self.splitter_three, 0, 0, 1, 2)
        self.stacked_widget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stacked_widget, 0, 0, 1, 2)

        self.retranslateUi(UserFinderGUI)
        self.stacked_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(UserFinderGUI)

    def retranslateUi(self, UserFinderGUI):
        _translate = QtCore.QCoreApplication.translate
        UserFinderGUI.setWindowTitle(_translate("UserFinderGUI", "User Finder"))
        self.progress_label.setText(_translate("UserFinderGUI", "Progress Label"))
        self.view_users_button.setText(_translate("UserFinderGUI", "View Users"))
        self.remove_subreddit_button.setText(_translate("UserFinderGUI", "-"))
        self.add_subreddit_button.setText(_translate("UserFinderGUI", "+"))
        self.label_3.setText(_translate("UserFinderGUI", "Subreddit Watchlist"))
        self.subreddit_watchlist_widget.setWhatsThis(_translate("UserFinderGUI", "A list of subreddits which tops posts will be examined to find users."))
        self.label_2.setText(_translate("UserFinderGUI", "Do Not Include List"))
        self.remove_user_button.setText(_translate("UserFinderGUI", "-"))
        self.add_user_button.setText(_translate("UserFinderGUI", "+"))
        self.user_blacklist_widget.setWhatsThis(_translate("UserFinderGUI", "A list of users who even if in the top posters for the subreddit list, will be ignored."))
        self.score_limit_spinbox.setToolTip(_translate("UserFinderGUI", "Only posts with a score above this number will be considered"))
        self.filter_by_score_checkbox.setToolTip(_translate("UserFinderGUI", "If checked, only posts above the designated score will be considered"))
        self.filter_by_score_checkbox.setText(_translate("UserFinderGUI", "Filter By Score"))
        self.post_limit_spinbox.setToolTip(_translate("UserFinderGUI", "The number of top posts that will be searched"))
        self.label_5.setToolTip(_translate("UserFinderGUI", "The number of top posts that are looked at to get users."))
        self.label_5.setText(_translate("UserFinderGUI", "Post Limit:"))
        self.top_sort_group_box.setTitle(_translate("UserFinderGUI", "Top Sort Period"))
        self.hour_radio.setText(_translate("UserFinderGUI", "Hour"))
        self.day_radio.setText(_translate("UserFinderGUI", "Day"))
        self.week_radio.setText(_translate("UserFinderGUI", "Week"))
        self.month_radio.setText(_translate("UserFinderGUI", "Month"))
        self.year_radio.setText(_translate("UserFinderGUI", "Year"))
        self.all_time_radio.setText(_translate("UserFinderGUI", "All Time"))
        self.run_button.setText(_translate("UserFinderGUI", "Run User Finder"))
        self.settings_button.setText(_translate("UserFinderGUI", "Settings"))
        self.user_finder_button.setText(_translate("UserFinderGUI", "User Finder"))

