# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resources\ui_files\user_auth_wizard.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserAuthWizard(object):
    def setupUi(self, UserAuthWizard):
        UserAuthWizard.setObjectName("UserAuthWizard")
        UserAuthWizard.resize(965, 682)
        UserAuthWizard.setWizardStyle(QtWidgets.QWizard.ModernStyle)
        self.wizardPage1 = QtWidgets.QWizardPage()
        self.wizardPage1.setObjectName("wizardPage1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.wizardPage1)
        self.verticalLayout.setSpacing(35)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.wizardPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.wizardPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.authorize_account_browser = QtWidgets.QTextBrowser(self.wizardPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authorize_account_browser.sizePolicy().hasHeightForWidth())
        self.authorize_account_browser.setSizePolicy(sizePolicy)
        self.authorize_account_browser.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.authorize_account_browser.setStyleSheet("text: rgb(0, 0, 255)")
        self.authorize_account_browser.setOpenExternalLinks(True)
        self.authorize_account_browser.setObjectName("authorize_account_browser")
        self.verticalLayout.addWidget(self.authorize_account_browser)
        self.label_6 = QtWidgets.QLabel(self.wizardPage1)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        UserAuthWizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtWidgets.QWizardPage()
        self.wizardPage2.setObjectName("wizardPage2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.wizardPage2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.wizardPage2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.auth_url_line_edit = QtWidgets.QLineEdit(self.wizardPage2)
        self.auth_url_line_edit.setObjectName("auth_url_line_edit")
        self.verticalLayout_2.addWidget(self.auth_url_line_edit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        UserAuthWizard.addPage(self.wizardPage2)
        self.wizardPage = QtWidgets.QWizardPage()
        self.wizardPage.setObjectName("wizardPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.wizardPage)
        self.verticalLayout_3.setSpacing(50)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.wizardPage)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.user_name_verification_label = QtWidgets.QLabel(self.wizardPage)
        self.user_name_verification_label.setObjectName("user_name_verification_label")
        self.horizontalLayout.addWidget(self.user_name_verification_label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.label_5 = QtWidgets.QLabel(self.wizardPage)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        UserAuthWizard.addPage(self.wizardPage)

        self.retranslateUi(UserAuthWizard)
        QtCore.QMetaObject.connectSlotsByName(UserAuthWizard)

    def retranslateUi(self, UserAuthWizard):
        _translate = QtCore.QCoreApplication.translate
        UserAuthWizard.setWindowTitle(_translate("UserAuthWizard", "Connect Your Reddit Account"))
        self.label.setText(_translate("UserAuthWizard", "<html><head/><body><p><span style=\" font-size:9pt;\">Follow the link below to connect your reddit account to The Downloader For Reddit.</span></p><p><span style=\" font-size:9pt;\">Once connected you should see increased download speeds, and more exciting features in the near future.</span></p></body></html>"))
        self.label_2.setText(_translate("UserAuthWizard", "<html><head/><body><p><span style=\" font-size:9pt;\">On clicking the link, your default browser will open to a reddit page asking if you want to allow this connectiong. Upon clicking &quot;Allow&quot;, you will be redirected to an empty localhost page. </span><span style=\" font-size:9pt; font-weight:600;\">This page will say it is unable to connect. This is intentional.</span></p><p><span style=\" font-size:9pt;\">Copy the url in the address bar and paste it in the input field on the next page.</span></p></body></html>"))
        self.label_6.setText(_translate("UserAuthWizard", "<html><head/><body><p><span style=\" font-weight:600;\">Note: </span>The token returned by reddit will have permenant access to your reddit acount that only you can disable through the reddit website. The token will be <span style=\" font-weight:600;\">lightly </span>encrypted and stored in your config file. A reasonably skilled attacker with access to your computer will be able to decrypt the token. It is only encrypted in the sense that someone accessing only the config file will not see the raw token. There is no way to completely secure a token on a stand-alone desktop application.</p><p>If you find this level of security to be unacceptable, do not complete this wizard.</p></body></html>"))
        self.label_3.setText(_translate("UserAuthWizard", "<html><head/><body><p><span style=\" font-size:10pt;\">Paste the entire url below:</span></p></body></html>"))
        self.label_4.setText(_translate("UserAuthWizard", "<html><head/><body><p><span style=\" font-size:10pt;\">If you see your reddit username below, your account is now linked.</span></p></body></html>"))
        self.user_name_verification_label.setText(_translate("UserAuthWizard", "<html><head/><body><p><span style=\" font-size:10pt;\">Username</span></p></body></html>"))
        self.label_5.setText(_translate("UserAuthWizard", "<html><head/><body><p>If this is not your username, you may need to go through this connection wizard again.</p></body></html>"))
