from .AbstractSettingsWidget import AbstractSettingsWidget
from .CoreSettingsWidget import CoreSettingsWidget
from .DisplaySettingsWidget import DisplaySettingsWidget
from .DownloadSettingsWidget import DownloadSettingsWidget
from .ImgurSettingsWidget import ImgurSettingsWidget
from .SettingsDialog import SettingsDialog
