"""empty message

Revision ID: 2abab33bb232
Revises: eeabe8b25e48
Create Date: 2020-04-28 09:50:37.919996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2abab33bb232'
down_revision = 'eeabe8b25e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download_session', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('download_session', 'duration')
    # ### end Alembic commands ###
