"""Add hash duplicate

Revision ID: 4476d8334855
Revises: 7c83ade12997
Create Date: 2025-06-03 08:07:11.399073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4476d8334855'
down_revision = '7c83ade12997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
