"""Add md5 hash

Revision ID: 7c83ade12997
Revises: cc19495248eb
Create Date: 2025-06-02 11:34:10.233088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c83ade12997'
down_revision = 'cc19495248eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_content_md5_hash'), 'content', ['md5_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_md5_hash'), table_name='content')
    # ### end Alembic commands ###
