"""empty message

Revision ID: a89ca2163290
Revises: d40138efefe5
Create Date: 2020-06-02 10:02:32.534828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89ca2163290'
down_revision = 'd40138efefe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_object', sa.Column('comment_file_format', sa.String(), nullable=True))
    op.add_column('reddit_object_list', sa.Column('comment_file_format', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_object_list', 'comment_file_format')
    op.drop_column('reddit_object', 'comment_file_format')
    # ### end Alembic commands ###
