"""Enhance duplicate controls

Revision ID: b838ef3372ca
Revises: 4476d8334855
Create Date: 2025-06-04 14:31:08.892435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b838ef3372ca'
down_revision = '4476d8334855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_object', sa.Column('duplicate_control_method', sa.Enum('KEEP', 'DELETE', 'MOVE', name='duplicatecontrolmethod'), nullable=True))
    op.add_column('reddit_object', sa.Column('duplicate_naming_method', sa.String(), nullable=True))
    op.add_column('reddit_object', sa.Column('duplicate_save_structure', sa.String(), nullable=True))
    op.add_column('reddit_object', sa.Column('hash_duplicates', sa.Boolean(), nullable=True))
    op.add_column('reddit_object_list', sa.Column('duplicate_control_method', sa.Enum('KEEP', 'DELETE', 'MOVE', name='duplicatecontrolmethod'), nullable=True))
    op.add_column('reddit_object_list', sa.Column('duplicate_naming_method', sa.String(), nullable=True))
    op.add_column('reddit_object_list', sa.Column('duplicate_save_structure', sa.String(), nullable=True))
    op.add_column('reddit_object_list', sa.Column('hash_duplicates', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_object_list', 'hash_duplicates')
    op.drop_column('reddit_object_list', 'duplicate_save_structure')
    op.drop_column('reddit_object_list', 'duplicate_naming_method')
    op.drop_column('reddit_object_list', 'duplicate_control_method')
    op.drop_column('reddit_object', 'hash_duplicates')
    op.drop_column('reddit_object', 'duplicate_save_structure')
    op.drop_column('reddit_object', 'duplicate_naming_method')
    op.drop_column('reddit_object', 'duplicate_control_method')
    # ### end Alembic commands ###
