"""empty message

Revision ID: c19eae85081c
Revises: a89ca2163290
Create Date: 2020-06-05 08:31:53.895215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c19eae85081c'
down_revision = 'a89ca2163290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download_task', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('download_task', 'active')
    # ### end Alembic commands ###
