"""Add md5 hash

Revision ID: cc19495248eb
Revises: ab46745cf45e
Create Date: 2025-05-30 11:20:56.164665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc19495248eb'
down_revision = 'ab46745cf45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('md5_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'md5_hash')
    # ### end Alembic commands ###
