"""Remove the 'last_download' field from reddit object model.

Revision ID: cc433ec81ed6
Revises: 2abab33bb232
Create Date: 2020-05-06 08:55:17.330236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc433ec81ed6'
down_revision = '2abab33bb232'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('reddit_object') as batch_op:
        batch_op.drop_column('last_download')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_object', sa.Column('last_download', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
