"""empty message

Revision ID: eeabe8b25e48
Revises: 
Create Date: 2020-04-24 10:23:58.877046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeabe8b25e48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_object_list', sa.Column('avoid_duplicates', sa.Boolean(), nullable=True))
    op.add_column('reddit_object_list', sa.Column('comment_limit', sa.Integer(), nullable=True))
    op.add_column('reddit_object_list', sa.Column('comment_naming_method', sa.String(), nullable=True))
    op.add_column('reddit_object_list', sa.Column('comment_save_structure', sa.String(), nullable=True))
    op.add_column('reddit_object_list', sa.Column('comment_score_limit', sa.Integer(), nullable=True))
    op.add_column('reddit_object_list', sa.Column('comment_score_limit_operator', sa.Enum('LESS_THAN', 'NO_LIMIT', 'GREATER_THAN', name='limitoperator'), nullable=True))
    op.add_column('reddit_object_list', sa.Column('comment_sort_method', sa.Enum('NEW', 'TOP', 'BEST', 'CONTROVERSIAL', 'OLD', 'Q_AND_A', name='commentsortmethod'), nullable=True))
    op.add_column('reddit_object_list', sa.Column('date_limit', sa.DateTime(), nullable=True))
    op.add_column('reddit_object_list', sa.Column('download_comment_content', sa.Enum('DOWNLOAD', 'DO_NOT_DOWNLOAD', 'DOWNLOAD_ONLY_AUTHOR', name='commentdownload'), nullable=True))
    op.add_column('reddit_object_list', sa.Column('download_comments', sa.Enum('DOWNLOAD', 'DO_NOT_DOWNLOAD', 'DOWNLOAD_ONLY_AUTHOR', name='commentdownload'), nullable=True))
    op.add_column('reddit_object_list', sa.Column('download_gifs', sa.Boolean(), nullable=True))
    op.add_column('reddit_object_list', sa.Column('download_images', sa.Boolean(), nullable=True))
    op.add_column('reddit_object_list', sa.Column('download_nsfw', sa.Enum('EXCLUDE', 'INCLUDE', 'ONLY', name='nsfwfilter'), nullable=True))
    op.add_column('reddit_object_list', sa.Column('download_self_post_text', sa.Boolean(), nullable=True))
    op.add_column('reddit_object_list', sa.Column('download_videos', sa.Boolean(), nullable=True))
    op.add_column('reddit_object_list', sa.Column('extract_comments', sa.Enum('DOWNLOAD', 'DO_NOT_DOWNLOAD', 'DOWNLOAD_ONLY_AUTHOR', name='commentdownload'), nullable=True))
    op.add_column('reddit_object_list', sa.Column('extract_self_post_links', sa.Boolean(), nullable=True))
    op.add_column('reddit_object_list', sa.Column('post_download_naming_method', sa.String(), nullable=True))
    op.add_column('reddit_object_list', sa.Column('post_limit', sa.SmallInteger(), nullable=True))
    op.add_column('reddit_object_list', sa.Column('post_save_structure', sa.String(), nullable=True))
    op.add_column('reddit_object_list', sa.Column('post_score_limit', sa.Integer(), nullable=True))
    op.add_column('reddit_object_list', sa.Column('post_score_limit_operator', sa.Enum('LESS_THAN', 'NO_LIMIT', 'GREATER_THAN', name='limitoperator'), nullable=True))
    op.add_column('reddit_object_list', sa.Column('post_sort_method', sa.Enum('NEW', 'HOT', 'RISING', 'CONTROVERSIAL', 'TOP_HOUR', 'TOP_DAY', 'TOP_WEEK', 'TOP_MONTH', 'TOP_YEAR', 'TOP_ALL', name='postsortmethod'), nullable=True))
    op.add_column('reddit_object_list', sa.Column('self_post_file_format', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_object_list', 'self_post_file_format')
    op.drop_column('reddit_object_list', 'post_sort_method')
    op.drop_column('reddit_object_list', 'post_score_limit_operator')
    op.drop_column('reddit_object_list', 'post_score_limit')
    op.drop_column('reddit_object_list', 'post_save_structure')
    op.drop_column('reddit_object_list', 'post_limit')
    op.drop_column('reddit_object_list', 'post_download_naming_method')
    op.drop_column('reddit_object_list', 'extract_self_post_links')
    op.drop_column('reddit_object_list', 'extract_comments')
    op.drop_column('reddit_object_list', 'download_videos')
    op.drop_column('reddit_object_list', 'download_self_post_text')
    op.drop_column('reddit_object_list', 'download_nsfw')
    op.drop_column('reddit_object_list', 'download_images')
    op.drop_column('reddit_object_list', 'download_gifs')
    op.drop_column('reddit_object_list', 'download_comments')
    op.drop_column('reddit_object_list', 'download_comment_content')
    op.drop_column('reddit_object_list', 'date_limit')
    op.drop_column('reddit_object_list', 'comment_sort_method')
    op.drop_column('reddit_object_list', 'comment_score_limit_operator')
    op.drop_column('reddit_object_list', 'comment_score_limit')
    op.drop_column('reddit_object_list', 'comment_save_structure')
    op.drop_column('reddit_object_list', 'comment_naming_method')
    op.drop_column('reddit_object_list', 'comment_limit')
    op.drop_column('reddit_object_list', 'avoid_duplicates')
    # ### end Alembic commands ###
