from enum import Enum


class Error(Enum):

    UNSUCCESSFUL_RESPONSE = 1
    UNSUPPORTED_DOMAIN = 2
    DOES_NOT_EXIST = 3
    FAILED_TO_LOCATE = 4
    FORBIDDEN = 5
    TEXT_LINK_FAILURE = 6
    FAILED_TO_EXTRACT = 7
    FAILED_SELF_POST = 8
    DUPLICATE_CONTENT = 9
    FAILED_FILTER = 10
    MULTIPART_FAILURE = 11
    UNKNOWN_ERROR = 12
    CONNECTION_ERROR = 13
    DOWNLOAD_STOPPED = 14
    TEXT_FAILURE = 15
    UNRECOGNIZED_EXTENSION = 16
    RATE_LIMIT_ERROR = 17
    CREDIT_ERROR = 18


# list of errors that should not be retried
NON_DOWNLOADABLE = [
    Error.UNSUPPORTED_DOMAIN,
    Error.DOES_NOT_EXIST,
    Error.FAILED_TO_LOCATE,
    Error.FORBIDDEN,
    Error.DUPLICATE_CONTENT,
]
