# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RedditDownloader_Settings_mac.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(513, 560)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Settings.sizePolicy().hasHeightForWidth())
        Settings.setSizePolicy(sizePolicy)
        Settings.setMinimumSize(QtCore.QSize(513, 560))
        Settings.setMaximumSize(QtCore.QSize(513, 560))
        font = QtGui.QFont()
        font.setPointSize(12)
        Settings.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/settings_single_gear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Settings.setWindowIcon(icon)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Settings)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(310, 10, 191, 61))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.accounts_group = QtWidgets.QGroupBox(self.gridLayoutWidget_2)
        self.accounts_group.setTitle("")
        self.accounts_group.setObjectName("accounts_group")
        self.imgur_client_button = QtWidgets.QPushButton(self.accounts_group)
        self.imgur_client_button.setGeometry(QtCore.QRect(10, 0, 161, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.imgur_client_button.setFont(font)
        self.imgur_client_button.setObjectName("imgur_client_button")
        self.reddit_account_link_button = QtWidgets.QPushButton(self.accounts_group)
        self.reddit_account_link_button.setGeometry(QtCore.QRect(10, 30, 161, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.reddit_account_link_button.setFont(font)
        self.reddit_account_link_button.setObjectName("reddit_account_link_button")
        self.gridLayout_2.addWidget(self.accounts_group, 2, 0, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(Settings)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 231, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.auto_save_checkbox = QtWidgets.QCheckBox(self.groupBox)
        self.auto_save_checkbox.setGeometry(QtCore.QRect(10, 0, 199, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.auto_save_checkbox.setFont(font)
        self.auto_save_checkbox.setObjectName("auto_save_checkbox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 85, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.backup_select_folder_button = QtWidgets.QPushButton(self.groupBox)
        self.backup_select_folder_button.setGeometry(QtCore.QRect(120, 30, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backup_select_folder_button.setFont(font)
        self.backup_select_folder_button.setObjectName("backup_select_folder_button")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 109, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.backup_import_file_button = QtWidgets.QPushButton(self.groupBox)
        self.backup_import_file_button.setGeometry(QtCore.QRect(120, 60, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backup_import_file_button.setFont(font)
        self.backup_import_file_button.setObjectName("backup_import_file_button")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(Settings)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 110, 491, 411))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.stackedWidget = QtWidgets.QStackedWidget(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.page)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 201, 91))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.score_group = QtWidgets.QGroupBox(self.gridLayoutWidget_3)
        self.score_group.setTitle("")
        self.score_group.setObjectName("score_group")
        self.restrict_to_score_checkbox = QtWidgets.QCheckBox(self.score_group)
        self.restrict_to_score_checkbox.setGeometry(QtCore.QRect(10, 10, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.restrict_to_score_checkbox.setFont(font)
        self.restrict_to_score_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.restrict_to_score_checkbox.setObjectName("restrict_to_score_checkbox")
        self.post_score_combo = QtWidgets.QComboBox(self.score_group)
        self.post_score_combo.setGeometry(QtCore.QRect(10, 50, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.post_score_combo.setFont(font)
        self.post_score_combo.setEditable(False)
        self.post_score_combo.setCurrentText("")
        self.post_score_combo.setObjectName("post_score_combo")
        self.post_score_limit_spin_box = QtWidgets.QSpinBox(self.score_group)
        self.post_score_limit_spin_box.setGeometry(QtCore.QRect(120, 50, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.post_score_limit_spin_box.setFont(font)
        self.post_score_limit_spin_box.setMaximum(100000)
        self.post_score_limit_spin_box.setObjectName("post_score_limit_spin_box")
        self.gridLayout_3.addWidget(self.score_group, 1, 0, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.page)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(220, 10, 261, 101))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.subreddit_sort_group = QtWidgets.QGroupBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.subreddit_sort_group.setFont(font)
        self.subreddit_sort_group.setObjectName("subreddit_sort_group")
        self.sub_sort_hot_radio = QtWidgets.QRadioButton(self.subreddit_sort_group)
        self.sub_sort_hot_radio.setGeometry(QtCore.QRect(10, 20, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sub_sort_hot_radio.setFont(font)
        self.sub_sort_hot_radio.setObjectName("sub_sort_hot_radio")
        self.sub_sort_rising_radio = QtWidgets.QRadioButton(self.subreddit_sort_group)
        self.sub_sort_rising_radio.setGeometry(QtCore.QRect(10, 40, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sub_sort_rising_radio.setFont(font)
        self.sub_sort_rising_radio.setObjectName("sub_sort_rising_radio")
        self.sub_sort_new_radio = QtWidgets.QRadioButton(self.subreddit_sort_group)
        self.sub_sort_new_radio.setGeometry(QtCore.QRect(140, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sub_sort_new_radio.setFont(font)
        self.sub_sort_new_radio.setObjectName("sub_sort_new_radio")
        self.sub_sort_top_radio = QtWidgets.QRadioButton(self.subreddit_sort_group)
        self.sub_sort_top_radio.setGeometry(QtCore.QRect(140, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sub_sort_top_radio.setFont(font)
        self.sub_sort_top_radio.setObjectName("sub_sort_top_radio")
        self.sub_sort_controversial_radio = QtWidgets.QRadioButton(self.subreddit_sort_group)
        self.sub_sort_controversial_radio.setGeometry(QtCore.QRect(10, 60, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sub_sort_controversial_radio.setFont(font)
        self.sub_sort_controversial_radio.setObjectName("sub_sort_controversial_radio")
        self.sub_sort_top_combo = QtWidgets.QComboBox(self.subreddit_sort_group)
        self.sub_sort_top_combo.setGeometry(QtCore.QRect(140, 60, 111, 21))
        self.sub_sort_top_combo.setObjectName("sub_sort_top_combo")
        self.gridLayout_5.addWidget(self.subreddit_sort_group, 2, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.page)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 120, 295, 31))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.post_limit_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.post_limit_label.setFont(font)
        self.post_limit_label.setObjectName("post_limit_label")
        self.gridLayout_4.addWidget(self.post_limit_label, 0, 0, 1, 1)
        self.post_limit_spinbox = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.post_limit_spinbox.setFont(font)
        self.post_limit_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.post_limit_spinbox.setAccelerated(True)
        self.post_limit_spinbox.setMinimum(1)
        self.post_limit_spinbox.setMaximum(1000)
        self.post_limit_spinbox.setProperty("value", 25)
        self.post_limit_spinbox.setObjectName("post_limit_spinbox")
        self.gridLayout_4.addWidget(self.post_limit_spinbox, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.page)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 220, 471, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.link_filter_video_checkbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.link_filter_video_checkbox.setGeometry(QtCore.QRect(10, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.link_filter_video_checkbox.setFont(font)
        self.link_filter_video_checkbox.setObjectName("link_filter_video_checkbox")
        self.link_filter_image_checkbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.link_filter_image_checkbox.setGeometry(QtCore.QRect(150, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.link_filter_image_checkbox.setFont(font)
        self.link_filter_image_checkbox.setObjectName("link_filter_image_checkbox")
        self.link_filter_avoid_duplicates_checkbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.link_filter_avoid_duplicates_checkbox.setGeometry(QtCore.QRect(300, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.link_filter_avoid_duplicates_checkbox.setFont(font)
        self.link_filter_avoid_duplicates_checkbox.setObjectName("link_filter_avoid_duplicates_checkbox")
        self.date_restriction_checkbox = QtWidgets.QCheckBox(self.page)
        self.date_restriction_checkbox.setGeometry(QtCore.QRect(20, 160, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.date_restriction_checkbox.setFont(font)
        self.date_restriction_checkbox.setObjectName("date_restriction_checkbox")
        self.subreddit_save_location_label = QtWidgets.QLabel(self.page)
        self.subreddit_save_location_label.setGeometry(QtCore.QRect(10, 280, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.subreddit_save_location_label.setFont(font)
        self.subreddit_save_location_label.setObjectName("subreddit_save_location_label")
        self.subreddit_save_by_combo = QtWidgets.QComboBox(self.page)
        self.subreddit_save_by_combo.setGeometry(QtCore.QRect(280, 280, 181, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.subreddit_save_by_combo.setFont(font)
        self.subreddit_save_by_combo.setObjectName("subreddit_save_by_combo")
        self.name_files_label = QtWidgets.QLabel(self.page)
        self.name_files_label.setGeometry(QtCore.QRect(10, 310, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name_files_label.setFont(font)
        self.name_files_label.setObjectName("name_files_label")
        self.name_downloads_by_combo = QtWidgets.QComboBox(self.page)
        self.name_downloads_by_combo.setGeometry(QtCore.QRect(280, 310, 181, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name_downloads_by_combo.setFont(font)
        self.name_downloads_by_combo.setObjectName("name_downloads_by_combo")
        self.save_directory_line_edit = QtWidgets.QLineEdit(self.page)
        self.save_directory_line_edit.setGeometry(QtCore.QRect(150, 340, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save_directory_line_edit.setFont(font)
        self.save_directory_line_edit.setObjectName("save_directory_line_edit")
        self.save_directory_dialog_button = QtWidgets.QPushButton(self.page)
        self.save_directory_dialog_button.setGeometry(QtCore.QRect(10, 342, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save_directory_dialog_button.setFont(font)
        self.save_directory_dialog_button.setObjectName("save_directory_dialog_button")
        self.restrict_by_custom_date_checkbox = QtWidgets.QCheckBox(self.page)
        self.restrict_by_custom_date_checkbox.setGeometry(QtCore.QRect(20, 190, 181, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.restrict_by_custom_date_checkbox.setFont(font)
        self.restrict_by_custom_date_checkbox.setObjectName("restrict_by_custom_date_checkbox")
        self.date_limit_edit = QtWidgets.QDateTimeEdit(self.page)
        self.date_limit_edit.setGeometry(QtCore.QRect(210, 190, 194, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.date_limit_edit.setFont(font)
        self.date_limit_edit.setCalendarPopup(True)
        self.date_limit_edit.setObjectName("date_limit_edit")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(10, 379, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.list_sort_combo = QtWidgets.QComboBox(self.page)
        self.list_sort_combo.setGeometry(QtCore.QRect(90, 380, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.list_sort_combo.setFont(font)
        self.list_sort_combo.setObjectName("list_sort_combo")
        self.list_sort_order_combo = QtWidgets.QComboBox(self.page)
        self.list_sort_order_combo.setGeometry(QtCore.QRect(270, 380, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.list_sort_order_combo.setFont(font)
        self.list_sort_order_combo.setObjectName("list_sort_order_combo")
        self.stackedWidget.addWidget(self.page)
        self.gridLayout_6.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.save_cancel_button_box = QtWidgets.QDialogButtonBox(Settings)
        self.save_cancel_button_box.setGeometry(QtCore.QRect(340, 520, 161, 41))
        self.save_cancel_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.save_cancel_button_box.setCenterButtons(False)
        self.save_cancel_button_box.setObjectName("save_cancel_button_box")
        self.total_files_downloaded_label = QtWidgets.QLabel(Settings)
        self.total_files_downloaded_label.setGeometry(QtCore.QRect(10, 530, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.total_files_downloaded_label.setFont(font)
        self.total_files_downloaded_label.setObjectName("total_files_downloaded_label")
        self.restore_defaults_button = QtWidgets.QPushButton(Settings)
        self.restore_defaults_button.setGeometry(QtCore.QRect(200, 532, 131, 21))
        self.restore_defaults_button.setObjectName("restore_defaults_button")

        self.retranslateUi(Settings)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Settings"))
        Settings.setWhatsThis(_translate("Settings", "<html><head/><body><p><span style=\" font-size:10pt;\">This is a section to watch subreddits for top posts, and add users to userlist that are in the top</span></p></body></html>"))
        self.imgur_client_button.setText(_translate("Settings", "Imgur Client Information"))
        self.reddit_account_link_button.setText(_translate("Settings", "Link Reddit Account"))
        self.auto_save_checkbox.setText(_translate("Settings", "Save Automatically On Close"))
        self.label.setText(_translate("Settings", "Backup Lists:"))
        self.backup_select_folder_button.setText(_translate("Settings", "Select Folder"))
        self.label_2.setText(_translate("Settings", "Import Backups:"))
        self.backup_import_file_button.setText(_translate("Settings", "Select File"))
        self.restrict_to_score_checkbox.setToolTip(_translate("Settings", "<html><head/><body><p><span style=\" font-size:10pt;\">If checked, posts will only be downloaded if they are above or below a certain score</span></p></body></html>"))
        self.restrict_to_score_checkbox.setText(_translate("Settings", "Restrict Download By Score"))
        self.subreddit_sort_group.setTitle(_translate("Settings", "Subreddit Sort Type"))
        self.sub_sort_hot_radio.setText(_translate("Settings", "Hot"))
        self.sub_sort_rising_radio.setText(_translate("Settings", "Rising"))
        self.sub_sort_new_radio.setText(_translate("Settings", "New"))
        self.sub_sort_top_radio.setText(_translate("Settings", "Top"))
        self.sub_sort_controversial_radio.setText(_translate("Settings", "Controversial"))
        self.post_limit_label.setText(_translate("Settings", "Post retreival Limit (Max: 1000)"))
        self.post_limit_spinbox.setToolTip(_translate("Settings", "<html><head/><body><p><span style=\" font-size:10pt;\">Sets the max number of posts to retrieve from Reddit.  The limit is 1000 posts (this limit is imposed by the reddit api)</span></p></body></html>"))
        self.groupBox_2.setTitle(_translate("Settings", "Link Filter"))
        self.link_filter_video_checkbox.setText(_translate("Settings", "Download Videos"))
        self.link_filter_image_checkbox.setText(_translate("Settings", "Download Images"))
        self.link_filter_avoid_duplicates_checkbox.setText(_translate("Settings", "Avoid Duplicates"))
        self.date_restriction_checkbox.setToolTip(_translate("Settings", "<html><head/><body><p><span style=\" font-size:10pt;\">If checked, only links that have been posted after the date of the last post downloaded by each user will be downloaded.</span></p></body></html>"))
        self.date_restriction_checkbox.setText(_translate("Settings", "Inforce User Date Limits"))
        self.subreddit_save_location_label.setText(_translate("Settings", "Subreddits save to folder designated by:"))
        self.name_files_label.setText(_translate("Settings", "Name downloaded files by:"))
        self.save_directory_dialog_button.setText(_translate("Settings", "Select Save Directory"))
        self.restrict_by_custom_date_checkbox.setText(_translate("Settings", "Restrict downloads by date:"))
        self.date_limit_edit.setDisplayFormat(_translate("Settings", "M/d/yyyy hh:mm:ss"))
        self.label_3.setText(_translate("Settings", "Sort lists by:"))
        self.total_files_downloaded_label.setText(_translate("Settings", "Total Files Downloaded: 0"))
        self.restore_defaults_button.setText(_translate("Settings", "Restore Defaults"))

