# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resources\ui_files\settings\database_settings_widget.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DatabaseSettingsWidget(object):
    def setupUi(self, DatabaseSettingsWidget):
        DatabaseSettingsWidget.setObjectName("DatabaseSettingsWidget")
        DatabaseSettingsWidget.resize(941, 740)
        self.verticalLayout = QtWidgets.QVBoxLayout(DatabaseSettingsWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.query_limit_groupbox = QtWidgets.QGroupBox(DatabaseSettingsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.query_limit_groupbox.sizePolicy().hasHeightForWidth())
        self.query_limit_groupbox.setSizePolicy(sizePolicy)
        self.query_limit_groupbox.setMinimumSize(QtCore.QSize(0, 0))
        self.query_limit_groupbox.setObjectName("query_limit_groupbox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.query_limit_groupbox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.query_limit_groupbox)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.query_limit_groupbox)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.query_limit_groupbox)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.query_limit_groupbox)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.query_limit_groupbox)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.download_session_query_limit_spinbox = QtWidgets.QSpinBox(self.query_limit_groupbox)
        self.download_session_query_limit_spinbox.setMinimumSize(QtCore.QSize(100, 0))
        self.download_session_query_limit_spinbox.setObjectName("download_session_query_limit_spinbox")
        self.horizontalLayout_5.addWidget(self.download_session_query_limit_spinbox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.reddit_object_query_limit_spinbox = QtWidgets.QSpinBox(self.query_limit_groupbox)
        self.reddit_object_query_limit_spinbox.setMinimumSize(QtCore.QSize(100, 0))
        self.reddit_object_query_limit_spinbox.setObjectName("reddit_object_query_limit_spinbox")
        self.horizontalLayout_4.addWidget(self.reddit_object_query_limit_spinbox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.post_query_limit_spinbox = QtWidgets.QSpinBox(self.query_limit_groupbox)
        self.post_query_limit_spinbox.setMinimumSize(QtCore.QSize(100, 0))
        self.post_query_limit_spinbox.setObjectName("post_query_limit_spinbox")
        self.horizontalLayout_3.addWidget(self.post_query_limit_spinbox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.content_query_limit_spinbox = QtWidgets.QSpinBox(self.query_limit_groupbox)
        self.content_query_limit_spinbox.setMinimumSize(QtCore.QSize(100, 0))
        self.content_query_limit_spinbox.setObjectName("content_query_limit_spinbox")
        self.horizontalLayout.addWidget(self.content_query_limit_spinbox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.formLayout_2.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comment_query_limit_spinbox = QtWidgets.QSpinBox(self.query_limit_groupbox)
        self.comment_query_limit_spinbox.setMinimumSize(QtCore.QSize(100, 0))
        self.comment_query_limit_spinbox.setObjectName("comment_query_limit_spinbox")
        self.horizontalLayout_2.addWidget(self.comment_query_limit_spinbox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.formLayout_2.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.horizontalLayout_6.addWidget(self.query_limit_groupbox)
        self.infinite_scroll_groupbox = QtWidgets.QGroupBox(DatabaseSettingsWidget)
        self.infinite_scroll_groupbox.setObjectName("infinite_scroll_groupbox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.infinite_scroll_groupbox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6.addWidget(self.infinite_scroll_groupbox)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)

        self.retranslateUi(DatabaseSettingsWidget)
        QtCore.QMetaObject.connectSlotsByName(DatabaseSettingsWidget)

    def retranslateUi(self, DatabaseSettingsWidget):
        _translate = QtCore.QCoreApplication.translate
        DatabaseSettingsWidget.setWindowTitle(_translate("DatabaseSettingsWidget", "Database View Settings"))
        self.query_limit_groupbox.setToolTip(_translate("DatabaseSettingsWidget", "<html><head/><body><p>Set the number of items that will be queried from the database per page when using a database view</p></body></html>"))
        self.query_limit_groupbox.setTitle(_translate("DatabaseSettingsWidget", "Query Limits"))
        self.label.setText(_translate("DatabaseSettingsWidget", "Download sessions:"))
        self.label_2.setText(_translate("DatabaseSettingsWidget", "Users/Subreddits:"))
        self.label_3.setText(_translate("DatabaseSettingsWidget", "Posts:"))
        self.label_4.setText(_translate("DatabaseSettingsWidget", "Content:"))
        self.label_5.setText(_translate("DatabaseSettingsWidget", "Comments:"))
        self.infinite_scroll_groupbox.setToolTip(_translate("DatabaseSettingsWidget", "<html><head/><body><p>If infinite scroll is enabled, the next page of queries will be loaded when the scroll bar reaches a load point near the bottom.  If this is not enabled, the next page must be loaded by clicking a button</p></body></html>"))
        self.infinite_scroll_groupbox.setTitle(_translate("DatabaseSettingsWidget", "Infinite Scroll"))
