# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resources\ui_files\settings\display_settings_widget.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DispalySettingsWidget(object):
    def setupUi(self, DispalySettingsWidget):
        DispalySettingsWidget.setObjectName("DispalySettingsWidget")
        DispalySettingsWidget.resize(906, 709)
        self.verticalLayout = QtWidgets.QVBoxLayout(DispalySettingsWidget)
        self.verticalLayout.setSpacing(16)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setVerticalSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(DispalySettingsWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.short_title_length_spin_box = QtWidgets.QSpinBox(DispalySettingsWidget)
        self.short_title_length_spin_box.setMinimumSize(QtCore.QSize(100, 0))
        self.short_title_length_spin_box.setObjectName("short_title_length_spin_box")
        self.horizontalLayout.addWidget(self.short_title_length_spin_box)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(DispalySettingsWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.schedule_countdown_combo = QtWidgets.QComboBox(DispalySettingsWidget)
        self.schedule_countdown_combo.setObjectName("schedule_countdown_combo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.schedule_countdown_combo)
        self.label_3 = QtWidgets.QLabel(DispalySettingsWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.scroll_to_last_added_checkbox = QtWidgets.QCheckBox(DispalySettingsWidget)
        self.scroll_to_last_added_checkbox.setText("")
        self.scroll_to_last_added_checkbox.setObjectName("scroll_to_last_added_checkbox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.scroll_to_last_added_checkbox)
        self.label_4 = QtWidgets.QLabel(DispalySettingsWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(DispalySettingsWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.colorize_new_checkbox = QtWidgets.QCheckBox(DispalySettingsWidget)
        self.colorize_new_checkbox.setText("")
        self.colorize_new_checkbox.setObjectName("colorize_new_checkbox")
        self.horizontalLayout_2.addWidget(self.colorize_new_checkbox)
        self.choose_new_color_button = QtWidgets.QPushButton(DispalySettingsWidget)
        self.choose_new_color_button.setMinimumSize(QtCore.QSize(140, 0))
        self.choose_new_color_button.setMaximumSize(QtCore.QSize(16777215, 26))
        self.choose_new_color_button.setObjectName("choose_new_color_button")
        self.horizontalLayout_2.addWidget(self.choose_new_color_button)
        self.new_ro_color_label = QtWidgets.QLabel(DispalySettingsWidget)
        self.new_ro_color_label.setObjectName("new_ro_color_label")
        self.horizontalLayout_2.addWidget(self.new_ro_color_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.colorize_disabled_checkbox = QtWidgets.QCheckBox(DispalySettingsWidget)
        self.colorize_disabled_checkbox.setText("")
        self.colorize_disabled_checkbox.setObjectName("colorize_disabled_checkbox")
        self.horizontalLayout_3.addWidget(self.colorize_disabled_checkbox)
        self.choose_disabled_color_button = QtWidgets.QPushButton(DispalySettingsWidget)
        self.choose_disabled_color_button.setMinimumSize(QtCore.QSize(140, 0))
        self.choose_disabled_color_button.setMaximumSize(QtCore.QSize(16777215, 26))
        self.choose_disabled_color_button.setObjectName("choose_disabled_color_button")
        self.horizontalLayout_3.addWidget(self.choose_disabled_color_button)
        self.disabled_ro_color_label = QtWidgets.QLabel(DispalySettingsWidget)
        self.disabled_ro_color_label.setObjectName("disabled_ro_color_label")
        self.horizontalLayout_3.addWidget(self.disabled_ro_color_label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.formLayout)
        self.tooltip_groupbox = QtWidgets.QGroupBox(DispalySettingsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tooltip_groupbox.sizePolicy().hasHeightForWidth())
        self.tooltip_groupbox.setSizePolicy(sizePolicy)
        self.tooltip_groupbox.setObjectName("tooltip_groupbox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tooltip_groupbox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout.addWidget(self.tooltip_groupbox)

        self.retranslateUi(DispalySettingsWidget)
        QtCore.QMetaObject.connectSlotsByName(DispalySettingsWidget)

    def retranslateUi(self, DispalySettingsWidget):
        _translate = QtCore.QCoreApplication.translate
        DispalySettingsWidget.setWindowTitle(_translate("DispalySettingsWidget", "Display Settings"))
        self.label.setToolTip(_translate("DispalySettingsWidget", "<html><head/><body><p>In most displays titles are shortened in order to display better. This dictates how many characters titles will be shortened to (set to &quot;0&quot; if you don\'t want titles shortened)</p></body></html>"))
        self.label.setText(_translate("DispalySettingsWidget", "Short title char length:"))
        self.label_2.setText(_translate("DispalySettingsWidget", "Display Schedule Countdown:"))
        self.label_3.setToolTip(_translate("DispalySettingsWidget", "<html><head/><body><p>When selected, the user/subreddit list will scroll to the new entry when a new user/subreddit is added</p></body></html>"))
        self.label_3.setText(_translate("DispalySettingsWidget", "Scoll to last added:"))
        self.label_4.setText(_translate("DispalySettingsWidget", "Colorize new users/subreddits:"))
        self.label_5.setText(_translate("DispalySettingsWidget", "Colorize disabled users/subreddits:"))
        self.choose_new_color_button.setText(_translate("DispalySettingsWidget", "Choose Color"))
        self.new_ro_color_label.setText(_translate("DispalySettingsWidget", "new user/subreddit color"))
        self.choose_disabled_color_button.setText(_translate("DispalySettingsWidget", "Choose Color"))
        self.disabled_ro_color_label.setText(_translate("DispalySettingsWidget", "disabled user/subreddit color"))
        self.tooltip_groupbox.setToolTip(_translate("DispalySettingsWidget", "<html><head/><body><p>These are user/subreddit attributes that will be displayed in a tooltip from the main window when the mouse is hovered over their name</p></body></html>"))
        self.tooltip_groupbox.setTitle(_translate("DispalySettingsWidget", "User/Subreddit Tooltip Display"))
