# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resources\ui_files\settings\download_settings_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DownloadSettingsWidget(object):
    def setupUi(self, DownloadSettingsWidget):
        DownloadSettingsWidget.setObjectName("DownloadSettingsWidget")
        DownloadSettingsWidget.resize(906, 709)
        self.verticalLayout = QtWidgets.QVBoxLayout(DownloadSettingsWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cascade_changes_checkbox = QtWidgets.QCheckBox(DownloadSettingsWidget)
        self.cascade_changes_checkbox.setObjectName("cascade_changes_checkbox")
        self.verticalLayout.addWidget(self.cascade_changes_checkbox)
        self.list_combo_box = QtWidgets.QComboBox(DownloadSettingsWidget)
        self.list_combo_box.setObjectName("list_combo_box")
        self.verticalLayout.addWidget(self.list_combo_box)
        self.scrollArea = QtWidgets.QScrollArea(DownloadSettingsWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 886, 635))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.list_settings_widget = ObjectSettingsWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_settings_widget.sizePolicy().hasHeightForWidth())
        self.list_settings_widget.setSizePolicy(sizePolicy)
        self.list_settings_widget.setObjectName("list_settings_widget")
        self.verticalLayout_2.addWidget(self.list_settings_widget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(DownloadSettingsWidget)
        QtCore.QMetaObject.connectSlotsByName(DownloadSettingsWidget)

    def retranslateUi(self, DownloadSettingsWidget):
        _translate = QtCore.QCoreApplication.translate
        DownloadSettingsWidget.setWindowTitle(_translate("DownloadSettingsWidget", "Download Default Settings"))
        self.cascade_changes_checkbox.setToolTip(_translate("DownloadSettingsWidget", "<html><head/><body><p>When selected, changes that are made to the selected list will cascade down to each user/subreddit in the list unless that user/subreddit has its settings locked</p></body></html>"))
        self.cascade_changes_checkbox.setText(_translate("DownloadSettingsWidget", "Cascade changes"))
from DownloaderForReddit.gui.widgets.object_settings_widget import ObjectSettingsWidget
