# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resources\ui_files\settings\schedule_settings_widget.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScheduleSettingsWidget(object):
    def setupUi(self, ScheduleSettingsWidget):
        ScheduleSettingsWidget.setObjectName("ScheduleSettingsWidget")
        ScheduleSettingsWidget.resize(906, 709)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(ScheduleSettingsWidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.perpetual_download_checkbox = QtWidgets.QCheckBox(ScheduleSettingsWidget)
        self.perpetual_download_checkbox.setObjectName("perpetual_download_checkbox")
        self.verticalLayout_7.addWidget(self.perpetual_download_checkbox)
        self.scheduling_group_box = QtWidgets.QGroupBox(ScheduleSettingsWidget)
        self.scheduling_group_box.setObjectName("scheduling_group_box")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scheduling_group_box)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.scheduling_group_box)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.label = QtWidgets.QLabel(self.scheduling_group_box)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.splitter = QtWidgets.QSplitter(self.scheduling_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.scheduled_downloads_list_widget = QtWidgets.QListWidget(self.splitter)
        self.scheduled_downloads_list_widget.setObjectName("scheduled_downloads_list_widget")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(15)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.error_label = QtWidgets.QLabel(self.widget)
        self.error_label.setStyleSheet("color: red")
        self.error_label.setObjectName("error_label")
        self.verticalLayout_5.addWidget(self.error_label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.interval_combo = QtWidgets.QComboBox(self.widget)
        self.interval_combo.setObjectName("interval_combo")
        self.verticalLayout.addWidget(self.interval_combo)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.interval_value_line_edit = QtWidgets.QLineEdit(self.widget)
        self.interval_value_line_edit.setObjectName("interval_value_line_edit")
        self.verticalLayout_2.addWidget(self.interval_value_line_edit)
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_6.setFont(font)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.user_list_combo = QtWidgets.QComboBox(self.widget)
        self.user_list_combo.setObjectName("user_list_combo")
        self.verticalLayout_3.addWidget(self.user_list_combo)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.subreddit_list_combo = QtWidgets.QComboBox(self.widget)
        self.subreddit_list_combo.setObjectName("subreddit_list_combo")
        self.verticalLayout_4.addWidget(self.subreddit_list_combo)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.schedule_download_button = QtWidgets.QPushButton(self.widget)
        self.schedule_download_button.setObjectName("schedule_download_button")
        self.verticalLayout_5.addWidget(self.schedule_download_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_6.addWidget(self.splitter)
        self.verticalLayout_7.addWidget(self.scheduling_group_box)

        self.retranslateUi(ScheduleSettingsWidget)
        QtCore.QMetaObject.connectSlotsByName(ScheduleSettingsWidget)

    def retranslateUi(self, ScheduleSettingsWidget):
        _translate = QtCore.QCoreApplication.translate
        ScheduleSettingsWidget.setWindowTitle(_translate("ScheduleSettingsWidget", "Schedule Settings"))
        self.perpetual_download_checkbox.setToolTip(_translate("ScheduleSettingsWidget", "<html><head/><body><p>If checked, a download session will not terminate itself when it makes it through a list, but will then restart at the beginning of the list and check for new downloads indefinitely until the application exits or one of the stop buttons is clicked</p></body></html>"))
        self.perpetual_download_checkbox.setText(_translate("ScheduleSettingsWidget", "Perpetual download"))
        self.scheduling_group_box.setTitle(_translate("ScheduleSettingsWidget", "Scheduling"))
        self.label_7.setText(_translate("ScheduleSettingsWidget", "<html><head/><body><p>Scheduled downloads will only be run if the application is open. If it comes time for a scheduled download to run and there is already a download in progress, the scheduled download will be skipped until next time.</p></body></html>"))
        self.label.setText(_translate("ScheduleSettingsWidget", "Scheduled Downloads:"))
        self.error_label.setText(_translate("ScheduleSettingsWidget", "Error Label"))
        self.label_2.setText(_translate("ScheduleSettingsWidget", "Download every:"))
        self.label_3.setText(_translate("ScheduleSettingsWidget", "at:"))
        self.label_6.setText(_translate("ScheduleSettingsWidget", "<html><head/><body><p>Enter in time format. </p><p>Ex: [Download every MINUTE at &quot;:20&quot;| download at the 20th second of every minute]</p><p>[Download every HOUR at &quot;10:25&quot;| download at the 25th second of the 10th minute of every hour]</p><p>[Download every MONDAY at &quot;6:42:55&quot;| download at this time every Monday]</p><p><br/></p></body></html>"))
        self.label_4.setText(_translate("ScheduleSettingsWidget", "User list:"))
        self.label_5.setText(_translate("ScheduleSettingsWidget", "Subreddit list:"))
        self.schedule_download_button.setText(_translate("ScheduleSettingsWidget", "Schedule Download"))
